let dict = {
  "common": {
    "第16回 東方Project 人気投票": "16th Touhou Project Popularity Poll",
    "開催期間": "Voting Period",
    "投票対象一覧": "List",
    "投票の決まり": "Rules",
    "よくある質問": "FAQ",
    "投票支援リンク集": "Cheering",
    "2020年6月7日（日）": "2020-06-07 (Sun)",
    "2020年6月13日（土）": "2020-06-13 (Sat)",

    "東方靈異伝": "Highly Responsive to Prayers",
    "東方封魔録": "Story of Eastern Wonderland",
    "東方夢時空": "Phantasmagoria of Dim.Dream",
    "東方幻想郷": "Lotus Land Story",
    "東方怪綺談": "Mystic Square",
    "東方紅魔郷": "Embodiment of Scarlet Devil",
    "東方妖々夢": "Perfect Cherry Blossom",
    "東方永夜抄": "Imperishable Night",
    "東方花映塚": "Phantasmagoria of Flower View",
    "東方文花帖": "Shoot the Bullet",
    "東方風神録": "Mountain of Faith",
    "東方地霊殿": "Subterranean Animism",
    "東方星蓮船": "Undefined Fantastic Object",
    "ダブルスポイラー": "Double Spoiler",
    "妖精大戦争": "Fairy Wars",
    "東方神霊廟": "Ten Desires",
    "東方輝針城": "Double Dealing Character",
    "弾幕アマノジャク": "Impossible Spell Card",
    "東方紺珠伝": "Legacy of Lunatic Kingdom",
    "東方天空璋": "Hidden Star in Four Seasons",
    "秘封ナイトメアダイアリー": "Violet Detector",
    "東方萃夢想": "Immaterial and Missing Power",
    "東方緋想天": "Scarlet Weather Rhapsody",
    "東方非想天則": "Touhou Hisoutensoku",
    "東方心綺楼": "Hopeless Masquerade",
    "東方深秘録": "Urban Legend in Limbo",
    "東方憑依華": "Antinomy of Common Flowers",
    "東方鬼形獣": "Wily Beast and Weakest Creature",
    "東方剛欲異聞": "Touhou Gouyoku Ibun",
    "幺樂団の歴史": "Akyu's Untouched Score",
    "蓬莱人形": "Dolls in Pseudo Paradise",
    "蓮台野夜行": "Ghostly Field Club",
    "夢違科学世紀": "Changeability of Strange Dream",
    "卯酉東海道": "Retrospective 53 minutes",
    "大空魔術": "Magical Astronomy",
    "未知の花　魅知の旅": "Unknown Flower, Mesmerizing Journey",
    "鳥船遺跡": "Trojan Green Asteroid",
    "伊弉諾物質": "Neo-traditionalism of Japan",
    "燕石博物誌": "Dr. Latency's Freak Report",
    "旧約酒場": "Dateless Bar \"Old Adam\"",
    "東方香霖堂": "Curiosities of Lotus Asia",
    "東方三月精": "Touhou Sangetsusei",
    "東方文花帖（書籍）": "Bohemian Archive in Japanese Red",
    "東方求聞史紀": "Perfect Memento in Strict Sense",
    "東方求聞史紀 / 東方求聞口授": "Perfect Memento in Strict Sense / Symposium of Post-mysticism",
    "東方儚月抄": "Touhou Bougetsushou",
    "The Grimoire of Marisa": "The Grimoire of Marisa",
    "東方茨歌仙": "Wild and Horned Hermit",
    "東方鈴奈庵": "Forbidden Scrollery",
    "東方文果真報": "Alternative Facts in Eastern Utopia",
    "The Grimoire of Usami 秘封倶楽部異界撮影記録": "The Grimoire of Usami",
    "東方智霊奇伝 反則探偵さとり": "Cheating Detective Satori",
    "東方酔蝶華": "Lotus Eaters",
    "東方Project人妖名鑑 宵闇編": "Who's Who of Humans & Youkai in Gensokyo"
  },

  "toho-vote.info/": {
    "投票を行う": "Go Vote",
    "投票する": "Vote!",
    "投票終了まで": "Voting Ends In:",
    "日": "d",
    "時間": "h",
    "分": "m",
    "秒": "s",
    "開催概要": "Summary",
    "東方Projectのキャラクター、音楽を対象とした人気投票です。\n\t\t投票の対象、投票の方法、また投票支援の方法などをご確認の上ご参加下さい。": "This is a popularity contest aimed at the Touhou Project characters and music. Feel free to participate after finding out who you can vote for, how to vote, and how to cheer for your favorites.",
    "過去の人気投票結果の一覧": "Previous Contest Results",
    "お問い合わせ": "Contact Us",
    "企画の流れ": "Schedule",
    "【支援しよう】": "【Let's Cheer!】",
    "　支援作品を登録して好きなキャラクタ・音楽・作品を応援（5/23 ～ 6/13）": "Cheering on your favorite characters/music/works by submitting content (5/23 ~ 6/13)",
    "【投票IDを発行】": "【Issue Voting ID】",
    "ID発行フォームにてメールアドレスを送信（6/6 12:00 ～ 6/13 23:59）": "Sending out Voting IDs by email through the ID Form (6/6 12:00 ~ 6/13 23:59)",
    "【投票しよう】": "【Let's Vote!】",
    "　入力したアドレスに届いた投票IDを使用し、各部門へ投票（6/7 0:00 ～ 6/13 23:59）": "Voting in polls using the Voting ID associated with your email (6/7 0:00 ~ 6/13 23:59)",
    "【結果の発表】": "【Publish Results】",
    "　速報は6/14予定。さらに後日、詳細な集計結果を発表": "The results summary is planned for 6/14. Following this, a breakdown of the results will be published later.",
    "投票用IDの発行": "Issue Voting ID",
    "投票用IDを発行する": "Request a Voting ID",
    "ただいまIDの発行のみ受け付けています。投票期間は2020年6月7日0時00分～6月13日23時59分です。": "Currently we are only issuing voting IDs. The voting period is from 2020-06-07 00:00 to 2020-06-13 23:59.",
    "投票開始まで": "Voting begins in:"
  },

  "toho-vote.info/form/": {
    "投票用IDの発行": "Voting IDs",
    "投票用IDを発行する": "Request a Voting ID",
    "投票の確認や修正を行う": "Vote Review / Edit",
    "投票する": "Vote",
    "人妖部門": "Character Poll",
    "音楽部門": "Music Poll",
    "作品部門": "Works Poll",
    "投票者アンケート": "Voter Questionnaire",
    "※回答は1人につき各部門1回までです。不正な回答を発見した場合は全て無効となります。": "※ Each person is only allowed one submission per poll. If multiple submissions are found, all of them will be voided.",
    "※複数のタブ・ウインドを開いての投票はエラーの原因となりますのでご遠慮ください。": "※ For this reason having multiple voting tabs/windows open may cause errors, so please refrain from doing so."
  },

  "toho-vote.info/form/id_issue.php": {
    "東方Project人気投票に投票するためには、投票用IDを発行する必要があります。": "In order to participate in the contest, you need to be issued a voting ID.",
    "また不正投票を防止する観点から、投票用IDの発行にはメールアドレスを必須としています。": "Additionally, in order to prevent cheating, voting IDs must be tied to an email address.",
    "下記のフォームにメールアドレスをご記入の上、発行ボタンを押してください。": "Please fill out the form below with your email address and hit the submit button.",
    "前回の投票IDの記入は任意ですので、未記入のままでも構いません（データチェック時の参考や結果発表時の統計として使用する予定です）。IDメールを再送信したい場合は記入不要です。": "You may optionally add a voting ID issued from a previous contest, which will be used for data checking and statistics purposes. If you wish to resend the voting ID email you do not need to re-add it.",
    "※前回投票IDはお問い合わせいただいても回答できません（メールアドレス情報は既に破棄しています）。": "※ Enquiries about previous contest voting IDs will be ignored, as the associated email information has already been discarded.",
    "メールアドレスを記入してください": "Please enter your email address",
    "前回の投票IDを記入してください（任意）": "Enter previous voter ID (Optional)",
    "上の画像の文字を入力してください": "Please enter the above characters",
    "送信": "Submit",
    "※フリーメールアドレスは非推奨ですがやむを得ない場合は可とします。": "Services granting temporary emails are not recommended but if it cannot be avoided they are allowed.",
    "※投票は1人につき各部門1回までです。多重投票と判断した投票は全て無効となります。": "Each person is only allowed one submission per poll. If multiple submissions are found, all of them will be voided.",
    "※その他細かいルールについては": "For other minor rules please refer to the ",
    "および": " as well as the ",
    "をご参照ください。": ".",
    "※迷惑メール設定を使用されている方は、｢@thwiki.info｣ドメインのメールを受信できるように設定してください。投票IDを記載したメールが届かない場合があります。": "※ If you have any spam filter for your email, please whitelist the \"@thwiki.info\" domain. Otherwise, the email with your voting ID may never be received.",
    "投票部門選択に戻る": "Return to Voting Category Menu"
  },

  "toho-vote.info/form/id_view.php": {
    "投票IDの確認": "Vote Review",
    "投票に使用したIDを入力してください": "Please enter your voter ID",
    "ID発行に使用したメールアドレスを入力してください": "Enter email linked with your voter ID",
    "送信": "Submit",
    "こちらでは投票情報の確認と修正が行えます。修正は1人につき各部門3回までとなりますので、ご注意ください。": "Here you can review and edit your voting data. Please be aware that you can only edit up to three times for all categories."
  },

  "toho-vote.info/form/vote_character.php": {
    "人妖部門投票": "Character Poll",
    "投票ID": "Voting ID",
    "必須": "Required",
    "発行された10桁の投票IDを記入ください": "Please input your 10-character voting ID",
    "名前（任意）": "Name (Optional)",
    "ハンドルネームも可能です": "Nicknames are OK",
    "最大7件まで投票できます（重複不可）。名前は25文字、コメントは最大200文字までとなります。": "You can vote for up to 7 characters (no duplicates). Names can be up to 25 characters, and comments can be 200 characters maximum.",
    "投票.1は一押し票として2票分のポイントとなります。": "Note, your #1 vote will count as 2 votes.",
    "投票.1": "Vote #1",
    "投票.2": "Vote #2",
    "投票.3": "Vote #3",
    "投票.4": "Vote #4",
    "投票.5": "Vote #5",
    "投票.6": "Vote #6",
    "投票.7": "Vote #7",
    "未選択": "Unselected",
    "コメント（任意）": "Comment (Optional)",
    "送信": "Submit",
    "投票部門選択に戻る": "Return to Voting Category Menu",

    "共通": "Common",
    "秘封倶楽部": "Secret Sealing Club",
    "東方求聞史紀": "Perfect Memento in Strict Sense",
    "その他（ゲーム）": "Others (Game)",
    "その他（書籍）": "Others (Books)",
    "その他（複合）": "Others (Misc.)",

    "博麗 霊夢": "Reimu Hakurei",
    "霧雨 魔理沙": "Marisa Kirisame",
    "ルーミア": "Rumia",
    "大妖精": "Daiyousei",
    "チルノ": "Cirno",
    "紅 美鈴": "Hong Meiling",
    "小悪魔": "Koakuma",
    "パチュリー・ノーレッジ": "Patchouli Knowledge",
    "十六夜 咲夜": "Sakuya Izayoi",
    "レミリア・スカーレット": "Remilia Scarlet",
    "フランドール・スカーレット": "Flandre Scarlet",
    "レティ・ホワイトロック": "Letty Whiterock",
    "橙": "Chen",
    "アリス・マーガトロイド": "Alice Margatroid",
    "リリーホワイト": "Lily White",
    "ルナサ・プリズムリバー": "Lunasa Prismriver",
    "メルラン・プリズムリバー": "Merlin Prismriver",
    "リリカ・プリズムリバー": "Lyrica Prismriver",
    "魂魄 妖夢": "Youmu Konpaku",
    "西行寺 幽々子": "Yuyuko Saigyouji",
    "八雲 藍": "Ran Yakumo",
    "八雲 紫": "Yukari Yakumo",
    "リグル・ナイトバグ": "Wriggle Nightbug",
    "ミスティア・ローレライ": "Mystia Lorelei",
    "上白沢 慧音": "Keine Kamishirasawa",
    "因幡 てゐ": "Tewi Inaba",
    "鈴仙・優曇華院・イナバ": "Reisen Udongein Inaba",
    "八意 永琳": "Eirin Yagokoro",
    "蓬莱山 輝夜": "Kaguya Houraisan",
    "藤原 妹紅": "Fujiwara no Mokou",
    "伊吹 萃香": "Suika Ibuki",
    "射命丸 文": "Aya Shameimaru",
    "メディスン・メランコリー": "Medicine Melancholy",
    "風見 幽香": "Yuuka Kazami",
    "小野塚 小町": "Komachi Onozuka",
    "四季映姫・ヤマザナドゥ": "Eiki Shiki, Yamaxanadu",
    "秋 静葉": "Shizuha Aki",
    "秋 穣子": "Minoriko Aki",
    "鍵山 雛": "Hina Kagiyama",
    "河城 にとり": "Nitori Kawashiro",
    "犬走 椛": "Momiji Inubashiri",
    "東風谷 早苗": "Sanae Kochiya",
    "八坂 神奈子": "Kanako Yasaka",
    "洩矢 諏訪子": "Suwako Moriya",
    "永江 衣玖": "Iku Nagae",
    "比那名居 天子": "Tenshi Hinanawi",
    "キスメ": "Kisume",
    "黒谷 ヤマメ": "Yamame Kurodani",
    "水橋 パルスィ": "Parsee Mizuhashi",
    "星熊 勇儀": "Yuugi Hoshiguma",
    "古明地 さとり": "Satori Komeiji",
    "火焔猫 燐": "Rin Kaenbyou",
    "霊烏路 空": "Utsuho Reiuji",
    "古明地 こいし": "Koishi Komeiji",
    "ナズーリン": "Nazrin",
    "多々良 小傘": "Kogasa Tatara",
    "雲居 一輪": "Ichirin Kumoi",
    "雲山": "Unzan",
    "村紗 水蜜": "Minamitsu Murasa",
    "寅丸 星": "Shou Toramaru",
    "聖 白蓮": "Byakuren Hijiri",
    "封獣 ぬえ": "Nue Houjuu",
    "大ナマズ": "Giant Catfish",
    "姫海棠 はたて": "Hatate Himekaidou",
    "幽谷 響子": "Kyouko Kasodani",
    "宮古 芳香": "Yoshika Miyako",
    "霍 青娥": "Seiga Kaku",
    "蘇我 屠自古": "Soga no Tojiko",
    "物部 布都": "Mononobe no Futo",
    "豊聡耳 神子": "Toyosatomimi no Miko",
    "二ッ岩 マミゾウ": "Mamizou Futatsuiwa",
    "秦 こころ": "Hata no Kokoro",
    "わかさぎ姫": "Wakasagihime",
    "赤蛮奇": "Sekibanki",
    "今泉 影狼": "Kagerou Imaizumi",
    "九十九 弁々": "Benben Tsukumo",
    "九十九 八橋": "Yatsuhashi Tsukumo",
    "鬼人 正邪": "Seija Kijin",
    "少名 針妙丸": "Shinmyoumaru Sukuna",
    "堀川 雷鼓": "Raiko Horikawa",
    "宇佐見 菫子": "Sumireko Usami",
    "清蘭": "Seiran",
    "鈴瑚": "Ringo",
    "ドレミー・スイート": "Doremy Sweet",
    "稀神 サグメ": "Sagume Kishin",
    "クラウンピース": "Clownpiece",
    "純狐": "Junko",
    "ヘカーティア・ラピスラズリ": "Hecatia Lapislazuli",
    "エタニティラルバ": "Eternity Larva",
    "坂田ネムノ": "Nemuno Sakata",
    "高麗野あうん": "Aunn Komano",
    "矢田寺成美": "Narumi Yatadera",
    "爾子田里乃": "Satono Nishida",
    "丁礼田舞": "Mai Teireida",
    "摩多羅隠岐奈": "Okina Matara",
    "依神女苑": "Joon Yorigami",
    "依神紫苑": "Shion Yorigami",
    "戎 瓔花": "Eika Ebisu",
    "牛崎 潤美": "Urumi Ushizaki",
    "庭渡 久侘歌": "Kutaka Niwatari",
    "吉弔 八千慧": "Yachie Kicchou",
    "杖刀偶 磨弓": "Mayumi Joutouguu",
    "埴安神 袿姫": "Keiki Haniyasushin",
    "驪駒 早鬼": "Saki Kurokoma",
    "オオカミ霊": "Wolf Spirit",
    "カワウソ霊": "Otter Spirit",
    "オオワシ霊": "Eagle Spirit",
    "シンギョク": "SinGyoku",
    "ユウゲンマガン": "YuugenMagan",
    "明羅": "Meira",
    "サリエル": "Sariel",
    "キクリ": "Kikuri",
    "コンガラ": "Konngara",
    "玄爺": "Genjii",
    "里香": "Rika",
    "エリス": "Elis",
    "魅魔": "Mima",
    "エレン": "Ellen",
    "小兎姫": "Kotohime",
    "カナ・アナベラル": "Kana Anaberal",
    "朝倉 理香子": "Rikako Asakura",
    "北白河 ちゆり": "Chiyuri Kitashirakawa",
    "岡崎 夢美": "Yumemi Okazaki",
    "オレンジ": "Orange",
    "くるみ": "Kurumi",
    "エリー": "Elly",
    "夢月": "Mugetsu",
    "幻月": "Gengetsu",
    "サラ": "Sara",
    "ルイズ": "Louise",
    "ユキ": "Yuki",
    "マイ": "Mai",
    "夢子": "Yumeko",
    "神綺": "Shinki",
    "蓬莱人形ジャケットイラストの娘": "Dolls in Pseudo Paradise CD Jacket Girl",
    "蓬莱人形レーベルイラストの娘": "Dolls in Pseudo Paradise CD Label Girl",
    "宇佐見 蓮子": "Renko Usami",
    "マエリベリー・ハーン": "Maribel Hearn",
    "稗田 阿求": "Hieda no Akyuu",
    "森近 霖之助": "Rinnosuke Morichika",
    "サニーミルク": "Sunny Milk",
    "ルナチャイルド": "Luna Child",
    "スターサファイア": "Star Sapphire",
    "綿月 豊姫": "Watatsuki no Toyohime",
    "綿月 依姫": "Watatsuki no Yorihime",
    "レイセン": "Reisen",
    "茨木 華扇": "Kasen Ibaraki",
    "影華扇（断善修悪の怪腕 - 茨木童子の腕）": "Shadow Kasen (Ibaraki Douji's Arm)",
    "鬼華扇（奸佞邪智の鬼）": "Oni Kasen (The Cunning and Treacherous Oni)",
    "本居 小鈴": "Kosuzu Motoori",
    "奥野田 美宵": "Miyoi Okunoda",
    "るーこと": "Ruukoto",
    "ミミちゃん": "Mimi-chan",
    "魂魄 妖忌": "Youki Konpaku",
    "レイラ・プリズムリバー": "Layla Prismriver",
    "核熱造神ヒソウテンソク": "Thermonuclear Deity Hisou Tensoku",
    "命蓮": "Myouren",
    "毘沙門天": "Bishamonten",
    "嫦娥": "Chang'e",
    "名無しの本読み妖怪": "Unnamed Book-Reading Youkai",
    "ツチノコ": "Tsuchinoko",
    "酒虫": "Sake Bug",
    "月の都の門番": "Moon Capital Gate Guards",
    "水江浦島子": "Mizue no Uranoshimako",
    "岩笠": "Unshou",
    "木花咲耶姫": "Konohana-Sakuyahime",
    "仙台四郎（福の神）": "Shirou Sendai",
    "運松": "Iwakasa",
    "座敷童": "Kutsutsura",
    "ホフゴブリン": "Hobgoblin",
    "万歳楽": "Manzairaku",
    "ヤマネ": "Unnamed Dormouse (Yamane)",
    "ケセランパサラン": "Keseran-pasaran",
    "小鈴の両親": "Kosuzu Motoori's Parents",
    "煙々羅": "Enenra",
    "チュパカブラ": "Tupai",
    "沓頬": "Zashiki-warashi",
    "ウワバミ": "Unnamed Snake Youkai",
    "易者": "Unnamed Jinyou (Fortune Teller)",
    "抗鬱薬おじさん": "Anxious Moustached Villager",
    "なめえもん": "Nameemon (Kosuzu's stuffed slug)",
    "塩屋敷の旦那": "Salt Merchant",
    "妖精（メイド妖精・ひまわり妖精 他）": "Fairy (Maid, Sunflower, etc.)",
    "幽霊（怨霊、神霊、化け化け含む）": "Ghosts (including vengeful spirits, divine spirits, bakebake)",
    "毛玉": "Kedama",
    "UFO（赤・青・緑、その他）": "UFOs (red, blue, green, etc.)",
    "兎（玉兎、永遠亭の妖怪兎 他）": "Rabbits (Moon rabbits, Eientei youkai rabbits, etc)",
    "狸（化け狸、野鉄砲他）": "Tanuki (Bake-danuki, Noteppou, etc)",
    "狐（妖怪狐、狐の子他）": "Kitsune (Youkai kitsune, Unnamed fox student, etc)",
    "カラス（地獄鴉、紫・文の使い魔 他）": "Crows (Hell ravens, Yukari and Aya's familiars, etc.)",
    "河童（山童含む）": "Kappa (including yamawaro)",
    "天狗（香霖堂の天狗、大天狗 他）": "Tengu (Kourindou Tengu, Great Tengu, etc)",
    "龍（子龍、邪龍 他）": "Dragons (Dragon child, Unnamed evil dragon, etc)",
    "里の人間（文花帖、求聞史紀、鈴奈庵などで登場した人間）": "Misc. Human Villagers (BAiJR, PMiSS, SoPM, FS, etc)",
    "アリスの人形（上海、蓬莱、大江戸 他）": "Alice's Dolls (Shanghai, Hourai, Ooedo, etc.)",
    "華扇の動物（久米、竿打、雷獣、彭祖、人面犬 他）": "Kasen's animals (Kume, Kanda, Raijuu, Houso, Jinkenmen, etc)",
    "神降ろしの神霊（天照、伊豆能売 他）": "Summoned Gods (Amaterasu, Izunome, etc.)",
    "都市伝説の怪異（お菊さん、八尺さま 他）": "Urban legend entities (Okiku-san, Hasshaku-sama)",
    "旧作名無し中ボス": "PC-98 Unnamed midbosses"
  },

  "toho-vote.info/form/vote_music.php": {
    "音楽部門投票": "Music Poll",
    "投票ID": "Voting ID",
    "必須": "Required",
    "発行された10桁の投票IDを記入ください": "Please input your 10-character voting ID",
    "名前（任意）": "Name (Optional)",
    "ハンドルネームも可能です": "Nicknames are OK",
    "最大10件まで投票できます（重複不可）。名前は25文字、コメントは最大200文字までとなります。": "You can vote for up to 10 music tracks (no duplicates). Names can be up to 25 characters, and comments can be 200 characters maximum.",
    "投票.1は一押し票として2票分のポイントとなります。": "Note, your #1 vote will count as 2 votes.",
    "セルフアレンジ曲および": "Self-arranges as well as ",
    "曲名違いのアレンジで同一票にまとめられる曲": "the listed tracks that are counted as the same",
    "は、順位集計上は同じ曲としてカウントしますが、どの作品の曲に何票投票されたかを併せて公表する予定です。": " will have their votes combined, but there will also be a breakdown of the votes for each version of the track in the results.",
    "投票.1": "Vote #1",
    "投票.2": "Vote #2",
    "投票.3": "Vote #3",
    "投票.4": "Vote #4",
    "投票.5": "Vote #5",
    "投票.6": "Vote #6",
    "投票.7": "Vote #7",
    "投票.8": "Vote #8",
    "投票.9": "Vote #9",
    "投票.10": "Vote #10",
    "未選択": "Unselected",
    "コメント（任意）": "Comment (Optional)",
    "送信": "Submit",
    "投票部門選択に戻る": "Return to Voting Category Menu",

    "東方深秘録（PS4版）": "Urban Legend in Limbo (PS4)",
    "秋霜玉": "Shuusou Gyoku",
    "稀翁玉": "Kioh Gyoku",
    "トルテルマジック": "Torte Le Magic",
    "神魔討綺伝": "Magus in Mystic Geometries",
    "黄昏酒場": "Uwabami Breakers",
    "東方幻想麻雀": "Touhou Unreal Mahjong",
    "その他・オリジナル": "Others / Original",

    "赤より紅い夢": "A Dream that Is More Scarlet than Red",
    "ほおずきみたいに紅い魂": "A Soul as Red as a Ground Cherry",
    "妖魔夜行": "Apparitions Stalk the Night",
    "ルーネイトエルフ": "Lunate Elf",
    "おてんば恋娘": "Tomboyish Girl in Love",
    "上海紅茶館　～ Chinese Tea": "Shanghai Teahouse ~ Chinese Tea",
    "明治十七年の上海アリス": "Shanghai Alice of Meiji 17",
    "ヴワル魔法図書館": "Voile, the Magic Library",
    "ラクトガール　～ 少女密室": "Locked Girl ~ The Girl's Secret Room",
    "メイドと血の懐中時計": "The Maid and the Pocket Watch of Blood",
    "月時計　～ ルナ・ダイアル": "Lunar Clock ~ Luna Dial",
    "ツェペシュの幼き末裔": "The Young Descendant of Tepes",
    "亡き王女の為のセプテット": "Septette for a Dead Princess",
    "魔法少女達の百年祭": "The Centennial Festival for Magical Girls",
    "U.N.オーエンは彼女なのか?": "U.N. Owen Was Her?",
    "紅より儚い永遠": "An Eternity that Is More Transient than Scarlet",
    "紅楼　～ Eastern Dream...": "Crimson Tower ~ Eastern Dream...",

    "妖々夢　～ Snow or Cherry Petal": "Mystic Dream ~ Snow or Cherry Petal",
    "無何有の郷　～ Deep Mountain": "Paradise ~ Deep Mountain",
    "クリスタライズシルバー": "Crystallized Silver",
    "遠野幻想物語": "The Fantastic Tales from Tono",
    "ティアオイエツォン(withered leaf)": "Diao ye zong (Withered Leaf)",
    "ブクレシュティの人形師": "The Doll Maker of Bucuresti",
    "人形裁判　～ 人の形弄びし少女": "Doll Judgment ~ The Girl who Played with People's Shapes",
    "天空の花の都": "The Capital City of Flowers in the Sky",
    "幽霊楽団　～ Phantom Ensemble": "Ghostly Band ~ Phantom Ensemble",
    "東方妖々夢　～ Ancient Temple": "Eastern Mystical Dream ~ Ancient Temple",
    "広有射怪鳥事　～ Till When?": "Hiroari Shoots a Strange Bird ~ Till When?",
    "アルティメットトゥルース": "Ultimate Truth",
    "幽雅に咲かせ、墨染の桜　～ Border of Life": "Bloom Nobly, Ink-Black Cherry Blossom ~ Border of Life",
    "ボーダーオブライフ": "Border of Life",
    "妖々跋扈": "Youkai Domination",
    "少女幻葬　～ Necro-Fantasy": "A Maiden's Illusionary Funeral ~ Necro-Fantasy",
    "妖々跋扈　～ Who done it!": "Youkai Domination ~ Who done it?",
    "ネクロファンタジア": "Necrofantasia",
    "春風の夢": "Dream of a Spring Breeze",
    "さくらさくら　～ Japanize Dream...": "Sakura, Sakura ~ Japanize Dream...",

    "永夜抄　～ Eastern Night.": "Eternal Night Vignette ~ Eastern Night.",
    "幻視の夜　～ Ghostly Eyes": "Illusionary Night ~ Ghostly Eyes",
    "蠢々秋月　～ Mooned Insect": "Stirring an Autumn Moon ~ Mooned Insect",
    "夜雀の歌声　～ Night Bird": "Song of the Night Sparrow ~ Night Bird",
    "もう歌しか聞こえない": "Deaf to All but the Song",
    "懐かしき東方の血　～ Old World": "Nostalgic Blood of the East ~ Old World",
    "プレインエイジア": "Plain Asia",
    "永夜の報い　～ Imperishable Night": "Retribution for the Eternal Night ~ Imperishable Night",
    "少女綺想曲　～ Dream Battle": "Maiden's Capriccio ~ Dream Battle",
    "恋色マスタースパーク": "Love-colored Master Spark",
    "シンデレラケージ　～ Kagome-Kagome": "Cinderella Cage ~ Kagome-Kagome",
    "狂気の瞳　～ Invisible Full Moon": "Lunatic Eyes ~ Invisible Full Moon",
    "ヴォヤージュ1969": "Voyage 1969",
    "千年幻想郷　～ History of the Moon": "Gensokyo Millennium ~ History of the Moon",
    "竹取飛翔　～ Lunatic Princess": "Flight in the Bamboo Cutter ~ Lunatic Princess",
    "ヴォヤージュ1970": "Voyage 1970",
    "エクステンドアッシュ　～ 蓬莱人": "Extend Ash ~ Person of Hourai",
    "月まで届け、不死の煙": "Reach for the Moon, Immortal Smoke",
    "月見草": "Evening Primrose",
    "Eternal Dream　～ 幽玄の槭樹": "Eternal Dream ~ Mystic Maple",
    "東方妖怪小町": "Eastern Youkai Beauty",

    "萃夢想": "Memory of Forgathering Dream",
    "東方妖恋談": "Eastern Mystical Love Consultation",
    "少女綺想曲 ～ Capriccio": "Maiden's Capriccio",
    "恋色マジック": "Love-coloured Magic",
    "魔女達の舞踏会": "The Witches' Ball",
    "メイドと血の懐中時計": "The Maid and the Pocket Watch of Blood",
    "月時計 ～ ルナ・ダイアル": "Lunar Clock ~ Lunar Dial",
    "ブクレシュティの人形師": "The Doll Maker of Bucuresti",
    "人形裁判": "Doll Judgment",
    "ラクトガール ～ 少女密室": "Locked Girl ~ Girl's Secret Room",
    "ヴワル魔法図書館": "Voile, the Magic Library",
    "広有射怪鳥事　～ Till When?": "Hiroari Shoots a Strange Bird ~ Till When?",
    "東方妖々夢 ～ Ancient Temple": "Eastern Mystical Dream ~ Ancient Temple",
    "亡き王女の為のセプテット": "Septette for a Dead Princess",
    "幽雅に咲かせ、墨染の桜 ～ Border of Life": "Bloom Nobly, Ink-Black Cherry Blossom ~ Border of Life",
    "Demystify Feast": "Demystify Feast",
    "夜が降りてくる ～ Evening Star": "Night Falls ~ Evening Star",
    "御伽の国の鬼が島　～ Missing Power": "Oni's Island in the Fairyland ~ Missing Power",
    "夏明き": "End of Summer",
    "東方萃夢想": "Eastern Memory of Forgathering Dream",
    "魔所": "Demonic Place",
    "月輪": "The Moon",
    "遍参": "Wanderings",
    "裏心": "Inner Heart",
    "Intermezzo": "Intermezzo",
    "あゆのかぜ": "Eastern Wind",
    "森閑": "Silence",
    "仰空": "Skygazer",
    "幽境": "Solitary Place",
    "珍客": "Unexpected Visitor",
    "紅夜": "Scarlet Night",
    "戦迅": "Swift Battle",
    "禍機": "Bad Omen",
    "砕月": "Broken Moon",

    "花映塚　～ Higan Retour": "Flower Viewing Mound ~ Higan Retour",
    "春色小径　～ Colorful Path": "Spring Lane ~ Colorful Path",
    "オリエンタルダークフライト": "Oriental Dark Flight",
    "フラワリングナイト": "Flowering Night",
    "東方妖々夢　～ Ancient Temple": "Eastern Mystical Dream ~ Ancient Temple",
    "狂気の瞳　～ Invisible Full Moon": "Lunatic Eyes ~ Invisible Full Moon",
    "おてんば恋娘の冒険": "Adventure of the Lovestruck Tomboy",
    "幽霊楽団　～ Phantom Ensemble": "Ghostly Band ~ Phantom Ensemble",
    "もう歌しか聞こえない　～ Flower Mix": "Deaf to All but the Song ~ Flower Mix",
    "お宇佐さまの素い幡": "White Flag of Usa Shrine",
    "風神少女　 (Short Version)": "Wind God Girl (Short Version)",
    "ポイズンボディ　～ Forsaken Doll": "Poison Body ~ Forsaken Doll",
    "今昔幻想郷　～ Flower Land": "Gensokyo, Past and Present ~ Flower Land",
    "彼岸帰航　～ Riverside View": "Higan Retour ~ Riverside View",
    "六十年目の東方裁判　～ Fate of Sixty Years": "Eastern Judgement in the Sixtieth Year ~ Fate of Sixty Years",
    "花の映る塚": "The Mound Where the Flowers Reflect",
    "此岸の塚": "Mound of Life",
    "花は幻想のままに": "The Flowers Remain in Fantasy",
    "魂の花　～ Another Dream...": "Flower of Soul ~ Another Dream...",

    "天狗の手帖　～ Mysterious Note": "Tengu's Notebook ~ Mysterious Note",
    "風の循環　～ Wind Tour": "Wind Circulation ~ Wind Tour",
    "天狗が見ている　～ Black Eyes": "Tengu is Watching ~ Black Eyes",
    "東の国の眠らない夜": "Sleepless Night of the Eastern Country",
    "レトロスペクティブ京都": "Retrospective Kyoto",
    "風神少女": "Wind God Girl",

    "封印されし神々": "Sealed Gods",
    "人恋し神様　～ Romantic Fall": "A God That Misses People ~ Romantic Fall",
    "稲田姫様に叱られるから": "Because Princess Inada Is Scolding Me",
    "厄神様の通り道　～ Dark Road": "The Road of the Misfortune God ~ Dark Road",
    "運命のダークサイド": "Dark Side of Fate",
    "神々が恋した幻想郷": "The Gensokyo The Gods Loved",
    "芥川龍之介の河童　～ Candid Friend": "Akutagawa Ryuunosuke's \"Kappa\" ~ Candid Friend",
    "フォールオブフォール　～ 秋めく滝": "Fall of Fall ~ Autumnal Waterfall",
    "妖怪の山　～ Mysterious Mountain": "The Youkai Mountain ~ Mysterious Mountain",
    "少女が見た日本の原風景": "The Primal Scene of Japan the Girl Saw",
    "信仰は儚き人間の為に": "Faith Is for the Transient People",
    "御柱の墓場　～ Grave of Being": "Cemetery of Onbashira ~ Grave of Being",
    "神さびた古戦場　～ Suwa Foughten Field": "The Venerable Ancient Battlefield ~ Suwa Foughten Field",
    "明日ハレの日、ケの昨日": "Tomorrow Will Be Special, Yesterday Was Not",
    "ネイティブフェイス": "Native Faith",
    "麓の神社": "Shrine at the Foot of the Mountain",
    "神は恵みの雨を降らす　～ Sylphid Dream": "The Gods Give Us Blessed Rain ~ Sylphid Dream",
    "プレイヤーズスコア": "Player's Score",

    "緋想天": "Heaven of Scarlet Perception",
    "日常坐臥": "Usual Days",
    "地の色は黄色": "The Ground's Color is Yellow",
    "甲論乙駁": "Argue for and Against",
    "風光明媚": "Beautiful Nature Sight",
    "香る樹葉花": "Fragrant Plants",
    "踊る水飛沫": "Dancing Water Spray",
    "以魚駆蠅": "Swing a Fish to Drive Away Flies",
    "放縦不羈": "Free and Easy",
    "嘲りの遊戯": "Ridiculous Game",
    "冷吟閑酔": "Drunk as I Like",
    "雲外蒼天": "Skies Beyond the Clouds",
    "黒い海に紅く　～ Legendary Fish": "Crimson in the Black Sea ~ Legendary Fish",
    "天衣無縫": "Flawless Clothing of the Celestials",
    "有頂天変　～ Wonderful Heaven": "Catastrophe in Bhavaagra ~ Wonderful Heaven",
    "幼心地の有頂天": "Bhavaagra As Seen Through a Child's Mind",
    "暮色蒼然": "Darkening Dusk",
    "東方緋想天": "Eastern Heaven of Scarlet Perception",
    "東方妖恋談": "Eastern Mystical Love Consultation",
    "星の器　～ Casket of Star": "Vessel of Stars ~ Casket of Star",
    "フラワリングナイト": "Flowering Night",
    "ブクレシュティの人形師": "The Doll Maker of Bucuresti",
    "広有射怪鳥事　～ Till When?": "Hiroari Shoots a Strange Bird ~ Till When?",
    "ラクトガール　～ 少女密室": "Locked Girl ~ The Girl's Secret Room",
    "幽雅に咲かせ、墨染の桜　～ Border of Life": "Bloom Nobly, Ink-Black Cherry Blossom ~ Border of Life",
    "亡き王女の為のセプテット": "Septette for a Dead Princess",
    "夜が降りてくる": "Night Falls",
    "砕月": "Broken Moon",
    "狂気の瞳　～ Invisible Full Moon": "Lunatic Eyes ~ Invisible Full Moon",
    "風神少女": "Wind God Girl",
    "彼岸帰航　～ Riverside View": "Higan Retour ~ Riverside View",

    "地霊達の起床": "Awakening of the Earth Spirits",
    "暗闇の風穴": "The Dark Blowhole",
    "封じられた妖怪　～ Lost Place": "The Sealed-Away Youkai ~ Lost Place",
    "渡る者の途絶えた橋": "The Bridge People No Longer Cross",
    "緑眼のジェラシー": "Green-Eyed Jealousy",
    "旧地獄街道を行く": "Walking the Streets of a Former Hell",
    "華のさかづき大江山": "A Flower-Studded Sake Dish on Mt. Ooe",
    "ハートフェルトファンシー": "Heartfelt Fancy",
    "少女さとり　～ 3rd eye": "Satori Maiden ~ 3rd eye",
    "廃獄ララバイ": "Lullaby of Deserted Hell",
    "死体旅行　～ Be of good cheer!": "Corpse Voyage ~ Be of good cheer!",
    "業火マントル": "Hellfire Mantle",
    "霊知の太陽信仰　～ Nuclear Fusion": "Solar Sect of Mystic Wisdom ~ Nuclear Fusion",
    "ラストリモート": "Last Remote",
    "ハルトマンの妖怪少女": "Hartmann's Youkai Girl",
    "地霊達の帰宅": "The Earth Spirits' Homecoming",
    "エネルギー黎明 ～ Future Dream...": "Energy Daybreak ~ Future Dream...",
    "プレイヤーズスコア": "Player's Score",

    "青空の影": "A Shadow in the Blue Sky",
    "春の湊に": "At the End of Spring",
    "小さな小さな賢将": "A Tiny, Tiny, Clever Commander",
    "閉ざせし雲の通い路": "The Sealed Cloud Route",
    "万年置き傘にご注意を": "Beware the Umbrella Left There Forever",
    "スカイルーイン": "Sky Ruin",
    "時代親父とハイカラ少女": "The Traditional Old Man and the Stylish Girl",
    "幽霊客船の時空を越えた旅": "Interdimensional Voyage of a Ghostly Passenger Ship",
    "キャプテン・ムラサ": "Captain Murasa",
    "魔界地方都市エソテリア": "Rural Makai City Esoteria",
    "虎柄の毘沙門天": "The Tiger-Patterned Vaisravana",
    "法界の火": "Fires of Hokkai",
    "感情の摩天楼　～ Cosmic Mind": "Emotional Skyscraper ~ Cosmic Mind",
    "夜空のユーフォーロマンス": "UFO Romance in the Night Sky",
    "平安のエイリアン": "Heian Alien",
    "妖怪寺": "Youkai Temple",
    "空の帰り道　～ Sky Dream": "Returning Home From the Sky ~ Sky Dream",
    "プレイヤーズスコア": "Player's Score",

    "君はあの影を見たか": "Did You See That Shadow?",
    "萃夢想": "Memory of Forgathering Dream",
    "伝説の巨神": "The Legendary Titan",
    "ぼくらの非想天則": "Our Hisoutensoku",
    "人形のある風景": "The Scenery of Living Dolls",
    "悠久の蒸気機関": "The Eternal Steam Engine",
    "信仰は儚き人間の為に": "Faith Is for the Transient People",
    "おてんば恋娘": "Tomboyish Girl in Love",
    "上海紅茶館　～ Chinese Tea": "Shanghai Teahouse ~ Chinese Tea",
    "霊知の太陽信仰　～ Nuclear Fusion": "Solar Sect of Mystic Wisdom ~ Nuclear Fusion",
    "明日ハレの日、ケの昨日": "Tomorrow Will Be Special, Yesterday Was Not",
    "二色蓮花蝶　～ Ancients": "Dichromatic Lotus Butterfly ~ Ancients",
    "恋色マジック": "Love-Coloured Magic",
    "the Grimoire of Alice": "the Grimoire of Alice",
    "ヴワル魔法図書館": "Voile, the Magic Library",
    "東方妖恋談": "Eastern Mystical Love Consultation",
    "アンノウンＸ　～ Unfound Adventure": "Unknown X ~ Unfound Adventure",
    "空に浮かぶ物体X": "X, the Floating Objects in the Sky",
    "巨大な影と小さな結末": "A Huge Shadow and a Tiny Conclusion",

    "ニュースハウンド": "Newshound",
    "あなたの町の怪事件": "The Mystery in Your Town",
    "妖怪モダンコロニー": "Youkai Modern Colony",
    "ネメシスの要塞": "Nemesis' Stronghold",
    "無間の鐘　～ Infinite Nightmare": "Bell of Avici ~ Infinite Nightmare",
    "妖怪の山　～ Mysterious Mountain": "The Youkai Mountain ~ Mysterious Mountain",

    "春の氷精": "An Ice Fairy in Spring",
    "可愛い大戦争のリフレーン": "The Refrain of the Lovely Great War",
    "いたずらに命をかけて": "Staking Your Life on a Prank",
    "年中夢中の好奇心": "Year-Round Absorbed Curiosity",
    "真夜中のフェアリーダンス": "A Midnight Fairy Dance",
    "妖精大戦争　～ Fairy Wars": "Great Fairy Wars ~ Fairy Wars",
    "ルーズレイン": "Loose Rain",
    "メイガスナイト": "Magus Night",
    "春の氷精　- 静 -": "An Ice Fairy in Spring - still -",
    "プレイヤーズスコア": "Player's Score",

    "欲深き霊魂": "Spirit of Avarice",
    "死霊の夜桜": "Night Sakura of Dead Spirits",
    "ゴーストリード": "Ghost Lead",
    "妖怪寺へようこそ": "Welcome to Youkai Temple",
    "門前の妖怪小娘": "Youkai Girl at the Gate",
    "素敵な墓場で暮しましょ": "Let’s live in a lovely Cemetery",
    "リジッドパラダイス": "Rigid Paradise",
    "デザイアドライブ": "Desire Drive",
    "古きユアンシェン": "Old Yuanxian",
    "夢殿大祀廟": "Dream Palace of the Great Mausoleum",
    "大神神話伝": "Omiwa Legend",
    "小さな欲望の星空": "Starry Sky of Small Desires",
    "聖徳伝説　～　True Administrator": "Shoutoku Legend ~ True Administrator",
    "妖怪裏参道": "Youkai Back Shrine Road",
    "佐渡の二ッ岩": "Futatsuiwa from Sado",
    "神社の新しい風": "A New Wind at the Shrine",
    "デザイアドリーム": "Desire Dream",
    "プレイヤーズスコア": "Player's Score",

    "春色小径　～ Colorful Path": "Spring Lane ~ Colorful Path",
    "メイガスナイト": "Magus Night",
    "時代親父とハイカラ少女": "The Traditional Old Man and the Stylish Girl",
    "感情の摩天楼　～ Cosmic Mind": "Emotional Skyscraper ~ Cosmic Mind",
    "大神神話伝": "Omiwa Legend",
    "聖徳伝説　～ True Administrator": "Shoutoku Legend ~ True Administrator",
    "芥川龍之介の河童　～ Candid Friend": "Akutagawa Ryuunosuke's \"Kappa\" ~ Candid Friend",
    "ハルトマンの妖怪少女": "Hartmann's Youkai Girl",
    "佐渡の二ッ岩": "Futatsuiwa from Sado",
    "幻想郷の二ッ岩": "Futatsuiwa from Gensokyo",
    "亡失のエモーション": "The Lost Emotion",
    "塵界不変のペシミズム": "This Dull World's Unchanging Pessimism",
    "心綺楼囃子": "Shinkirou Orchestra",
    "人気のある場所": "A Popular Location",
    "人気のない場所": "An Unpopular Location",
    "丑三つ時の里": "The Village in the Dead of Night",
    "本日の一面記事": "Today's Front-Page Headline",
    "暁雲": "Morning Clouds",
    "官板黄昏新聞": "Officially-Sanctioned Twilight Newspaper",
    "心綺楼祭囃子": "Shinkirou Festival Orchestra",
    "演者選択": "Performer Selection",
    "使われなかった場所": "An Unused Location",

    "不思議なお祓い棒": "Mysterious Purification Rod",
    "ミストレイク": "Mist Lake",
    "秘境のマーメイド": "Mermaid from the Uncharted Land",
    "運河を行き交う人妖": "Humans and Youkai Coming and Going at the Canal",
    "柳の下のデュラハン": "Dullahan Under the Willows",
    "満月の竹林": "Bamboo Forest of the Full Moon",
    "孤独なウェアウルフ": "Lonesome Werewolf",
    "マジカルストーム": "Magical Storm",
    "幻想浄瑠璃": "Illusionary Joururi",
    "空中に沈む輝針城": "The Shining Needle Castle Sinking in the Air",
    "リバースイデオロギー": "Reverse Ideology",
    "針小棒大の天守閣": "The Exaggerated Castle Keep",
    "輝く針の小人族　～ Little Princess": "Inchlings of the Shining Needle ~ Little Princess",
    "魔力の雷雲": "Thunderclouds of Magical Power",
    "始原のビート　～ Pristine Beat": "Primordial Beat ~ Pristine Beat",
    "小槌の魔力": "Magical Power of the Mallet",
    "不思議な不思議な道具達": "Strange, Strange Instruments",
    "プレイヤーズスコア": "Player's Score",

    "反則の狼煙を上げろ": "Raise the Signal Fire of Cheating",
    "秘境のマーメイド": "Mermaid from the Uncharted Land",
    "不可能弾幕には反則を": "Cheat Against the Impossible Danmaku",
    "リバースイデオロギー": "Reverse Ideology",
    "ミッドナイトスペルカード": "Midnight Spell Card",
    "幻想浄瑠璃": "Illusionary Joururi",
    "ロマンチック逃飛行": "Romantic Escape Flight",
    "妖怪の山　～ Mysterious Mountain": "The Youkai Mountain ~ Mysterious Mountain",
    "永遠の三日天下": "Eternal Short-Lived Reign",

    "二色蓮花蝶　～ Red and White": "Dichromatic Lotus Butterfly ~ Red and White",
    "恋色マスタースパーク": "Love-Coloured Master Spark",
    "時代親父とハイカラ少女": "The Traditional Old Man and the Stylish Girl",
    "感情の摩天楼　～ Cosmic Mind": "Emotional Skyscraper ~ Cosmic Mind",
    "大神神話伝": "Omiwa Legend",
    "聖徳伝説　～ True Administrator": "Shoutoku Legend ~ True Administrator",
    "芥川龍之介の河童　～ Candid Friend": "Akutagawa Ryuunosuke's \"Kappa\" ~ Candid Friend",
    "ハルトマンの妖怪少女": "Hartmann's Youkai Girl",
    "幻想郷の二ッ岩": "Futatsuiwa from Gensokyo",
    "亡失のエモーション": "The Lost Emotion",
    "月まで届け、不死の煙": "Reach for the Moon, Immortal Smoke",
    "輝く針の小人族　～ Little Princess": "Inchlings of the Shining Needle ~ Little Princess",
    "心揺さぶる都市伝説": "Heart-Stirring Urban Legends",
    "幻想郷ふしぎ発見": "Gensokyo Mystery Discovery",
    "ボールのある日常": "An Everyday Life with Balls",
    "顕現した伝承の形": "Forms of Manifested Folklore",
    "時代の風の訪れ": "Arrival of the Winds of the Era",
    "価値がわからない": "The Value Is Unrealized",
    "可能性を信じて": "Believe in Possibilities",
    "真実を知る者": "Those Who Know the Truth",
    "外界フォークロア": "Outside World Folklore",
    "各々の結末": "Each Ending",
    "明かされる深秘": "The Arcane Is Revealed",
    "オカルトアラカルト": "Occult à la Carte",
    "七玉蒐集ショウダウン": "Seven-Orb Collection Showdown",
    "公正なる奪い合い": "Fair Scramble",
    "対蹠地の鐘": "Bell of the Antipodes",
    "竹林インフレイム": "Bamboo Forest in Flames",
    "華狭間のバトルフィールド": "Battlefield of the Flower Threshold",
    "ラストオカルティズム　～ 現し世の秘術師": "Last Occultism ~ Esotericist of the Present World",

    "宇宙巫女現る": "The Space Shrine Maiden Appears",
    "忘れがたき、よすがの緑": "Unforgettable, the Nostalgic Greenery",
    "兎は舞い降りた": "The Rabbit Has Landed",
    "湖は浄めの月光を映して": "The Lake Reflects the Cleansed Moonlight",
    "九月のパンプキン": "September Pumpkin",
    "宇宙を飛ぶ不思議な巫女": "The Mysterious Shrine Maiden Flying Through Space",
    "永遠の春夢": "Eternal Spring Dream",
    "凍り付いた永遠の都": "The Frozen Eternal Capital",
    "逆転するホイールオブフォーチュン": "The Reversed Wheel of Fortune",
    "遥か38万キロのボヤージュ": "Faraway 380,000-Kilometer Voyage",
    "星条旗のピエロ": "The Pierrot of the Star-Spangled Banner",
    "故郷の星が映る海": "The Sea Where the Home Planet is Reflected",
    "ピュアヒューリーズ　～　心の在処": "Pure Furies ~ Whereabouts of the Heart",
    "見た事も無い悪夢の世界": "A Never-Before-Seen World of Nightmares",
    "パンデモニックプラネット": "Pandemonic Planet",
    "神社から見える月": "The Moon as Seen from the Shrine",
    "宇宙巫女帰還する": "The Space Shrine Maiden Returns Home",
    "プレイヤーズスコア": "Player's Score",

    "狂気の瞳　～ Invisible Full Moon": "Lunatic Eyes ~ Invisible Full Moon",
    "ネオ竹林インフレイム": "Neo Bamboo Forest in Flames",
    "億万劫の鐘": "Bell of Aeons",
    "オカルトアトラクト": "Occult Attract",
    "境界フォークロア": "Boundary Folklore",
    "アンノウンX　～ Occultly Madness": "Unknown X ~ Occultly Madness",
    "相貌の狂い ～ Horrible Night": "Madness of Lunatic Visages ~ Horrible Night",

    "桜舞い散る天空": "The Sky Where Cherry Blossoms Flutter Down",
    "希望の星は青霄に昇る": "A Star of Hope Rises in the Blue Sky",
    "真夏の妖精の夢": "A Midsummer Fairy's Dream",
    "色無き風は妖怪の山に": "The Colorless Wind on Youkai Mountain",
    "山奥のエンカウンター": "Deep-Mountain Encounter",
    "桜色の海を泳いで": "Swim in a Cherry Blossom-Colored Sea",
    "一対の神獣": "A Pair of Divine Beasts",
    "幻想のホワイトトラベラー": "Illusionary White Traveler",
    "魔法の笠地蔵": "The Magic Straw-Hat Ksitigarbha",
    "禁断の扉の向こうは、この世かあの世か": "Does the Forbidden Door Lead to This World, or the World Beyond?",
    "クレイジーバックダンサーズ": "Crazy Backup Dancers",
    "イントゥ・バックドア": "Into Backdoor",
    "秘匿されたフォーシーズンズ": "The Concealed Four Seasons",
    "もうドアには入れない": "No More Going Through Doors",
    "秘神マターラ　～ Hidden Star in All Seasons.": "Secret God Matara ~ Hidden Star in All Seasons.",
    "不自然な自然": "Unnatural Nature",
    "白い旅人": "White Traveler",
    "プレイヤーズスコア": "Player's Score",

    "地の色は黄色　～Primrose": "The Ground's Color is Yellow ~ Primrose",
    "マッシュルーム・ワルツ": "Mushroom Waltz",
    "聖輦船空を往く": "The Palanquin Ship Flies in the Sky",
    "法力の下の平等": "Equality Under the Law of Dharma",
    "恒常不変の参廟祀": "Constant and Unchanging Mazureum",
    "光輝く天球儀": "Shining Heavenly Armillary",
    "沢の河童の技術力": "The Ravine Kappa's Technological Prowess",
    "地底に咲く薔薇": "A Rose Blooming in the Underworld",
    "深緑の狸森にて": "In the Deep-Green Tanuki Forest",
    "心綺楼演舞": "Shinkirou Theatrical",
    "不滅のレッドソウル": "Immortal Red Soul",
    "落日に生える逆さ城": "The Inverted Castle Lit by the Setting Sun",
    "千の試練を超えて": "Overcome a Thousand Trials",
    "夢世界フォークロア": "Dream World Folklore",
    "永遠に続く回廊": "Corridor Stretching to Eternity",
    "スリープシープ・パレード": "Sleep Sheep Parade",
    "至る有頂天": "Bhavaagra as Far as the Eye Can See",
    "憑坐は夢と現の間に　～ Necro-Fantasia": "Yorimashi Between Dreams and Reality ~ Necro-Fantasia",
    "今宵は飄逸なエゴイスト(Live ver)　～ Egoistic Flowers.": "Tonight Stars an Easygoing Egoist (Live ver.) ~ Egoistic Flowers.",
    "オカルトアトラクト": "Occult Attract",
    "ネオ竹林インフレイム": "Neo Bamboo Forest in Flames",
    "億万劫の鐘": "Bell of a Billion Kalpas",
    "アンノウンX　～ Occultly Madness": "Unknown X ~ Occultly Madness",
    "輝く針の小人族　～ Little Princess": "Inchlings of the Shining Needle ~ Little Princess",
    "華狭間のバトルフィールド": "Battlefield of the Flower Threshold",
    "ラストオカルティズム　～ 現し世の秘術師": "Last Occultism ~ Esotericist of the Present World",
    "狂気の瞳　～ Invisible Full Moon": "Lunatic Eyes ~ Invisible Full Moon",
    "永遠の春夢": "Eternal Spring Dream",
    "有頂天変　～ Wonderful Heaven": "Catastrophe in Bhavaagra ~ Wonderful Heaven",
    "夜が降りてくる　～ Evening Star": "Night Falls ~ Evening Star",
    "憑依投合": "Being Things Eye To Eye",
    "連帯責人": "The One Jointly Responsible",
    "合縁奇縁": "An Odd Couple",
    "異心同体": "Two Minds of One Body",
    "壮言大語": "Big Talk",
    "知略縦横": "Scheming Outside the Box",
    "意気揚々": "In High Spirits",
    "開演間近": "The Curtain Shall Rise Soon",
    "天衣無縫　～\u00a0Yellow\u00a0Lily": "Flawless Clothing of the Celestials ~ Yellow Lily",
    "行雲流水": "Floating with the Tide",
    "異変の種子": "Seeds of the Incident",
    "疑惑の芽生え": "Sprouts of Suspicion",
    "未だ蕾む憑依華": "Possession Flowers Yet to Bud",
    "真相へ繋がる枝葉": "Branches Reaching to the Truth",
    "咲き誇る憑依華": "Possession Flowers in Full Bloom",
    "舞い散る憑依華吹雪": "Blizzard of Scattering Possession Flowers",
    "悠久の蒸気機関": "The Eternal Steam Engine",

    "悪夢日記": "Nightmare Journal",
    "ルーシッドドリーマー": "Lucid Dreamer",
    "ルナティックドリーマー": "Lunatic Dreamer",
    "ナイトメアダイアリー": "Nightmare Diary",
    "バー・オールドアダム": "Old Adam Bar",
    "燕石博物誌が連れてきた闇": "The Darkness Brought In by Swallowstone Naturalis Historia",
    "永遠の春夢": "Eternal Spring Dream",
    "秘匿されたフォーシーズンズ": "The Concealed Four Seasons",


    "物言わぬ獣の霊": "Silent Beast Spirits",
    "地蔵だけが知る哀嘆": "The Lamentations Known Only by Jizo",
    "ジェリーストーン": "Jelly Stone",
    "ロストリバー": "Lost River",
    "石の赤子と水中の牛": "The Stone Baby and the Submerged Bovine",
    "不朽の曼珠沙華": "Everlasting Red Spider Lily",
    "セラフィックチキン": "Seraphic Chicken",
    "アンロケイテッドヘル": "Unlocated Hell",
    "トータスドラゴン　〜幸運と不運": "Tortoise Dragon ~ Fortune and Misfortune",
    "ビーストメトロポリス": "Beast Metropolis",
    "セラミックスの杖刀人": "Joutoujin of Ceramics",
    "エレクトリックヘリテージ": "Electric Heritage",
    "偶像に世界を委ねて　〜Idoratrize World": "Entrust this World to Idols ~ Idolatrize World",
    "輝かしき弱肉強食の掟": "The Shining Law of the Strong Eating the Weak",
    "聖徳太子のペガサス　〜Dark Pegasus": "Prince Shoutoku's Pegasus ~ Dark Pegasus",
    "畜生達の休息": "The Animals' Rest",
    "地下からの帰還": "Returning Home from the Underground",

    "A Sacred Lot": "A Sacred Lot",
    "永遠の巫女": "Eternal Shrine Maiden",
    "The Positive and Negative": "The Positive and Negative",
    "Highly Responsive to Prayers": "Highly Responsive to Prayers",
    "東方怪奇談": "Eastern Strange Discourse",
    "天使伝説": "Angel's Legend",
    "Oriental Magician": "Oriental Magician",
    "破邪の小太刀": "Blade of Banishment",
    "魔鏡": "Magic Mirror",
    "the Legend of KAGE": "the Legend of KAGE",
    "いざ、倒れ逝くその時まで": "Now, Until the Moment You Die",
    "Civilization of Magic": "Civilization of Magic / We Shall Die Together",
    "星幽剣士（星幽天使）": "Swordsman of a Distant Star / Angel of a Distant Star",
    "アイリス": "Iris",
    "風の神社": "Shrine of the Wind",

    "東方封魔録　～ 浄土曼荼羅": "Eastern Recorded Sealing of a Demon ~ Pure Land Mandala",
    "博麗　～ Eastern Wind": "Hakurei ~ Eastern Wind ",
    "She's in a temper!!": "She's in a temper!!",
    "End of Daylight": "End of Daylight",
    "やみのちから": "Power of Darkness ",
    "幻夢界": "World of Empty Dreams ",
    "死を賭して": "Bet on Death",
    "ひもろぎ、むらさきにもえ": "Himorogi, Burn in Violet ",
    "恋色マジック": "Love-coloured Magic",
    "東方封魔録　～ 幽幻乱舞": "Eastern Recorded Sealing of a Demon ~ A Phantom's Boisterous Dance",
    "Complete Darkness": "Complete Darkness",
    "エキストララブ": "Extra Love",
    "戦車むすめのみるゆめ": "The Tank Girl's Dream",
    "遠野の森": "Forest of Tono",
    "昔話わんだーらんど": "Legendary Wonderland",
    "博麗神社境内": "Hakurei Shrine Grounds",
    "陽落ちて": "Sunfall",
    "封魔終演": "Sealed Demon's Finale",

    "夢は時空を越えて": "A Dream Transcending Space-time",
    "Selection": "Selection",
    "東方妖恋談": "Eastern Mystical Love Consultation",
    "Reincarnation": "Reincarnation",
    "Dim. Dream": "Dim. Dream",
    "Tabula rasa　～ 空白少女": "Tabula rasa ~ The Empty Girl",
    "Maniacal Princess": "Maniacal Princess",
    "夢消失　～ Lost Dream": "Vanishing Dream ~ Lost Dream",
    "夢幻遊戯　～ Dream War": "Visionary Game ~ Dream War",
    "魔法決戦！　～ Fight it out!": "Decisive Magic Battle! ~ Fight it out!",
    "Sailor of Time": "Sailor of Time",
    "Strawberry Crisis!!": "Strawberry Crisis!!",
    "非統一魔法世界論": "Disunified Field Theory of Magic",
    "魔法鐘愛": "Adoration of Magic",
    "久遠の夢": "Dream of Eternity",
    "東方の青い空": "Eastern Blue Sky",
    "永遠の満月": "Eternal Full Moon",
    "Maple Dream...": "Maple Dream...",
    "霊人の休日": "Ghostly Person's Holiday",
    "勝利デモ": "Victory Demonstration",
    "ゲームオーバー": "Game Over",
    "時の風": "Winds of Time",
    "スターボウドリーム": "Starbow Dream",
    "Phantasmagoria": "Phantasmagoria",

    "幻想郷　～ Lotus Land Story": "Gensokyo ~ Lotus Land Story",
    "Witching Dream": "Witching Dream",
    "Selene's Light": "Selene's Light",
    "装飾戦　～ Decoration Battle": "Decoration Battle",
    "Break the Sabbath": "Break the Sabbath",
    "紅響曲　～ Scarlet Phoneme": "Scarlet Symphony ~ Scarlet Phoneme",
    "Bad Apple!!": "Bad Apple!!",
    "霊戦　～ Perdition crisis": "Spirit Battle ~ Perdition crisis",
    "アリスマエステラ": "Alice Maestra",
    "少女綺想曲　～ Capriccio": "Maiden's Capriccio",
    "星の器　～ Casket of Star": "Vessel of Stars ~ Casket of Star",
    "Lotus Love": "Lotus Love",
    "眠れる恐怖　～ Sleeping Terror": "Sleeping Terror",
    "Dream Land": "Dream Land",
    "幽夢　～ Inanimate Dream": "Faint Dream ~ Inanimate Dream",
    "禁じざるをえない遊戯": "The Inevitably Forbidden Game",
    "メイド幻想　～ Icemilk Magic": "Illusion of a Maid ~ Icemilk Magic",
    "かわいい悪魔　～ Innocence": "Cute Devil ~ Innocence",
    "Days": "Days",
    "Peaceful": "Peaceful",
    "Arcadian Dream": "Arcadian Dream",
    "幻想の住人": "Those Who Live in Illusions",
    "Lotus Road": "Lotus Road",
    "Dreamy pilot": "Dreamy pilot",
    "Incomplete Plot": "Incomplete Plot",
    "Border Land": "Border Land",
    "Magic Shop of Raspberry": "Magic Shop of Raspberry",
    "Crescent Dream": "Crescent Dream",

    "怪綺談　～ Mystic Square": "Wondrous Tales of Romance ~ Mystic Square",
    "Dream Express": "Dream Express",
    "魔法陣　～ Magic Square": "Magic Formation ~ Magic Square",
    "夢想時空": "Dimension of Reverie",
    "霊天　～ Spiritual Heaven": "Spiritual Heaven",
    "Romantic Children": "Romantic Children",
    "プラスチックマインド": "Plastic Mind",
    "メイプルワイズ": "Maple Wise",
    "禁断の魔法　～ Forbidden Magic": "Forbidden Magic",
    "真紅の少女　～ Crimson Dead!!": "Crimson Maiden ~ Crimson Dead!!",
    "裏切りの少女　～ Judas Kiss": "Treacherous Maiden ~ Judas Kiss",
    "the Last Judgement": "the Last Judgement",
    "悲しき人形　～ Doll of Misery": "Doll of Misery",
    "世界の果て　～ World's End": "End of the World ~ World's End",
    "神話幻想　～ Infinite Being": "Legendary Illusion ~ Infinite Being",
    "不思議の国のアリス": "Alice in Wonderland",
    "the Grimoire of Alice": "the Grimoire of Alice",
    "神社": "Shinto Shrine",
    "Endless": "Endless",
    "久遠の楽園": "Eternal Paradise",
    "Mystic Dream": "Mystic Dream",
    "Peaceful Romancer": "Peaceful Romancer",
    "魂の休らむ所": "Soul's Resting Place",

    "テーマ・オブ・イースタンストーリー": "Theme of Eastern Story",

    "風神少女": "Wind God Girl",
    "おてんば恋娘の冒険": "Adventure of the Lovestruck Tomboy",
    "花映塚　～ after Higan Retour": "Flower Viewing Mound ~ after Higan Retour",

    "ジャパニーズサーガ": "Japanese Saga",
    "阿礼の子供": "Child of Are",
    "夜の鳩山を飛ぶ‐Power Mix": "Fly above Hatoyama at night - Power Mix",

    "サニールチルフレクション": "Sunny Rutile Flection",
    "夜だから眠れない": "Can't Sleep Because It's Nighttime",
    "妖精燦々として": "Like the Brilliance of Fairies",
    "サニーミルクの紅霧異変": "Sunny Milk's Scarlet Mist Incident",
    "雪月桜花の国": "A Land Resplendent With Nature's Beauty",
    "スターヴォヤージュ2008": "Star Voyage 2008",
    "可愛い大戦争のリフレーン": "The Refrain of the Lovely Great War",
    "フェアリー冒険譚": "The Fairy's Adventurous Tale",
    "二つの世界": "Two Worlds",

    "神域のかくれんぼ暮らし": "The Hide-and-Seek Lifestyle at the Shrine",
    "妖怪モダンコロニー": "Youkai Modern Colony",
    "年中夢中の好奇心": "Year-Round Absorbed Curiosity",
    "真夜中のフェアリーダンス": "A Midnight Fairy Dance",
    "妖精大戦争　～ Fairy Wars": "Great Fairy Wars ~ Fairy Wars",
    "メイガスナイト": "Magus Night",
    "古きユアンシェン": "Old Yuanxian",

    "妖怪宇宙旅行": "Youkai Space Travel",
    "綿月のスペルカード　～ Lunatic Blue": "Watatsuki's Spell Card ~ Lunatic Blue",
    "呑んべぇのレムリア (Retro Ver)": "A Drunkard's Lemuria (Retro Ver)",

    "魔法使いの憂鬱": "Magician's Melancholy",
    "スプートニク幻夜": "Illusionary Sputnik Night",

    "判読眼のビブロフィリア": "Bibliophile with a Deciphering Eye",
    "運河を行き交う人妖": "Humans and Youkai Traversing the Canal",
    "兎は舞い降りた": "The Rabbit Has Landed",

    "蓬莱伝説": "Legend of Hourai",
    "二色蓮花蝶　～ Red and White": "Dichromatic Lotus Butterfly ~ Red and White",
    "桜花之恋塚　～ Japanese Flower": "Lovely Mound of Cherry Blossoms ~ Japanese Flower",
    "明治十七年の上海アリス": "Shanghai Alice of Meiji 17",
    "東方怪奇談": "Eastern Strange Discourse",
    "エニグマティクドール": "Enigmatic Doll",
    "サーカスレヴァリエ": "Circus Reverie",
    "人形の森": "Forest of Dolls",
    "Witch of Love Potion": "Witch of Love Potion",
    "リーインカーネイション": "Reincarnation",
    "U.N.オーエンは彼女なのか？": "U.N. Owen Was Her?",
    "永遠の巫女": "Eternal Shrine Maiden",
    "空飛ぶ巫女の不思議な毎日": "The Strange Everyday Life of the Flying Shrine Maiden",

    "夜のデンデラ野を逝く": "Dying in the Dendera Fields in the Night",
    "少女秘封倶楽部": "Girls' Sealing Club",
    "東方妖々夢　～ Ancient Temple": "Eastern Mystical Dream ~ Ancient Temple",
    "古の冥界寺": "Ancient Temple of the Netherworld",
    "幻視の夜　～ Ghostly Eyes": "Illusionary Night ~ Ghostly Eyes",
    "魔術師メリー": "Merry the Magician",
    "月の妖鳥、化猫の幻": "Strange Bird of the Moon, Illusion of the Mysterious Cat",
    "過去の花　～ Fairy of Flower": "Flower of Past Days ~ Fairy of Flower",
    "魔法少女十字軍": "Magical Girl Crusade",
    "少女幻葬　～ Necro-Fantasy": "A Maiden's Illusionary Funeral ~ Necro-Fantasy",
    "幻想の永遠祭": "Eternal Festival of Illusions",

    "童祭　～ Innocent Treasures": "Kid's Festival ~ Innocent Treasures",
    "華胥の夢": "Dream of Arcadia",
    "上海紅茶館　～ Chinese Tea": "Shanghai Teahouse ~ Chinese Tea",
    "ヴォヤージュ1969": "Voyage 1969",
    "科学世紀の少年少女": "Boys and Girls of a Science Era",
    "永夜の報い　～ Imperishable Night": "Retribution for the Eternal Night ~ Imperishable Night",
    "夜が降りてくる　～ Evening Star": "Night Falls ~ Evening Star",
    "人形裁判　～ 人の形弄びし少女": "Doll Judgment ~ The Girl who Played with People's Shapes",
    "夢と現の境界": "Border Between Dreams and Reality",
    "幻想機械　～ Phantom Factory": "Phantasm Machine ~ Phantom Factory",
    "幽玄の槭樹　～ Eternal Dream": "Mystical Maple ~ Eternal Dream",

    "ヒロシゲ36号　～ Neo Super-Express": "Hiroshige No.36 ~ Neo Super-Express",
    "53ミニッツの青い海": "Blue Sea of 53 Minutes",
    "竹取飛翔　～ Lunatic Princess": "Flight in the Bamboo Cutter ~ Lunatic Princess",
    "彼岸帰航　～ Riverside View": "Higan Retour ~ Riverside View",
    "青木ヶ原の伝説": "Legend of Aokigahara",
    "お宇佐さまの素い幡": "White Flag of Usa Shrine",
    "月まで届け不死の煙": "Reach for the Moon, Immortal Smoke (Retrospective 53 minutes)",
    "レトロスペクティブ京都": "Retrospective Kyoto",
    "ラクトガール　～ 少女密室": "Locked Girl ~ The Girl's Secret Room",
    "千年幻想郷　～ History of the Moon": "Gensokyo Millennium ~ History of the Moon",
    "最も澄みわたる空と海": "The Purest Sky and Sea",

    "月面ツアーへようこそ": "Welcome to the Moon Tour",
    "天空のグリニッジ": "Greenwich in the Sky",
    "東の国の眠らない夜": "Sleepless Night of the Eastern Country",
    "車椅子の未来宇宙": "The Wheelchair's Future in Space",
    "Demystify Feast": "Demystify Feast",
    "衛星カフェテラス": "Satellite Café Terrace",
    "G Free": "G Free",
    "大空魔術　～ Magical Astronomy": "Celestial Wizardry ~ Magical Astronomy",
    "ネクロファンタジア": "Necrofantasia",
    "向こう側の月": "The Far Side of the Moon",

    "未知の花 魅知の旅": "Unknown Flower, Mesmerizing Journey",
    "無間の鐘　～ Infinite Nightmare": "Bell of Avici ~ Infinite Nightmare",
    "明日ハレの日、ケの昨日": "Tomorrow Will Be Special, Yesterday Was Not",

    "衛星トリフネ": "Satellite TORIFUNE",
    "トロヤ群の密林": "Trojan Asteroid Jungle",
    "デザイアドライブ": "Desire Drive",
    "フェアリー冒険譚": "The Fairies' Adventurous Tale",
    "天鳥船神社": "Ame-no-torifune Shrine",
    "夜空のユーフォーロマンス": "UFO Romance in the Night Sky",
    "ハルトマンの妖怪少女": "Hartmann's Youkai Girl",
    "天鳥船神社の結界": "The Barrier of Ame-no-torifune Shrine",
    "感情の摩天楼　～ Cosmic Mind": "Emotional Skyscraper ~ Cosmic Mind",
    "宇宙に浮かぶ幻想郷": "The Gensokyo That Floats in Outer Space",

    "緑のサナトリウム": "Green Sanatorium",
    "牛に引かれて善光寺参り": "Led On by a Cow to Visit Zenkou Temple",
    "ハートフェルトファンシー": "Heartfelt Fancy",
    "六十年目の東方裁判　～ Fate of Sixty Years": "Eastern Judgement in the Sixtieth Year ~ Fate of Sixty Years",
    "アガルタの風": "Wind of Agartha",
    "イザナギオブジェクト": "Izanagi Object",
    "妖怪裏参道": "Youkai Back Shrine Road",
    "アンノウンX　～ Unfound Adventure": "Unknown X ~ Unfound Adventure",
    "日本中の不思議を集めて": "Gathering the Mysterious from All Around Japan",
    "素敵な墓場で暮しましょ": "Let's Live in a Lovely Cemetery",

    "他愛も無い二人の博物誌": "The Childlike Duo's Naturalis Historia",
    "凍り付いた永遠の都": "The Frozen Eternal Capital",
    "Dr.レイテンシーの眠れなくなる瞳": "Dr. Latency's Sleepless Eyes",
    "九月のパンプキン": "September Pumpkin",
    "須臾はプランクを超えて": "The Instant is Shorter Than Planck Time",
    "シュレディンガーの化猫": "Schrödinger's Bakeneko",
    "空中に沈む輝針城": "The Shining Needle Castle Sinking in the Air",
    "禁忌の膜壁": "The Taboo Membrane Wall",
    "故郷の星が映る海": "The Sea Where the Home Planet is Reflected",
    "ピュアヒューリーズ　～ 心の在処": "Pure Furies ~ Whereabouts of the Heart",
    "永遠の三日天下": "Eternal Short-Lived Reign",

    "バー・オールドアダム": "Old Adam Bar",
    "燕石博物誌が連れてきた闇": "The Darkness Brought In by Swallowstone Naturalis Historia",
    "リバースイデオロギー": "Reverse Ideology",
    "アウトサイダーカクテル": "Outsider Cocktail",
    "大神神話伝": "Omiwa Legend",
    "パンデモニックプラネット": "Pandemonic Planet",
    "旧世界の冒険酒場": "Adventurer's Tavern of the Old World",
    "魔界地方都市エソテリア": "Rural Makai City Esoteria",
    "亡失のエモーション": "The Lost Emotion",
    "二日酔いの同床異夢": "Hangover of Bedfellows Dreaming Differently",

    "秋霜玉　～ Clockworks": "Shuusou Gyoku ~ Clockworks",
    "フォルスストロベリー": "False Strawberry",
    "プリムローズシヴァ": "Primrose Shiver",
    "幻想帝都": "Illusory Imperial Capital",
    "ディザストラスジェミニ": "Disastrous Gemini",
    "華の幻想　紅夢の宙": "Illusion of Flowers, Air of Scarlet Dream",
    "天空アーミー": "Firmament Army",
    "スプートニク幻夜": "Illusionary Sputnik Night",
    "機械サーカス　～ Reverie": "Mechanical Circus ~ Reverie",
    "カナベラルの夢幻少女": "Illusionary Girl from Canaveral",
    "魔法少女十字軍": "Magical Girl's Crusade",
    "アンティークテラー": "Antique Terror",
    "夢機械　～ Innocent Power": "Dream Machine ~ Innocent Power",
    "幻想科学　～ Doll's Phantom": "Illusory Science ~ Doll's Phantom",
    "少女神性　～ Pandora's Box": "Girl's Divinity ~ Pandora's Box",
    "シルクロードアリス": "Silk Road Alice",
    "魔女達の舞踏会　～ Magus": "The Witches' Ball ~ Magus",
    "二色蓮花蝶　～ Ancients": "Dichromatic Lotus Butterfly ~ Ancients",
    "ハーセルヴズ": "Herselves",
    "タイトルドメイド": "Titled Maid",

    "稀翁玉　～ Fairy Dance": "Kioh Gyoku ~ Fairy Dance",
    "天鵞絨少女戦　～ Velvet Battle": "Velvet Maiden Battle ~ Velvet Battle",
    "Castle Explorer -in the Sky-": "Castle Explorer -in the Sky-",
    "オルフェの詩　～ Pseudoclassic": "Orphic Poetry ~ Pseudoclassic",
    "新幻想　～ New Fantasy": "New Illusion ~ New Fantasy",
    "オルレアンの聖騎士": "Holy Knight of Orléans",
    "My Maid, Sweet Maid": "My Maid, Sweet Maid",
    "桜花之恋塚　～ Flower of Japan": "Lovely Mound of Cherry Blossoms ~ Flower of Japan",
    "乙女戦士　～ Heart of Valkyrie": "Warrior Maiden ~ Heart of Valkyrie",
    "エニグマティクドール　～ God Knows": "Enigmatic Doll ~ God Knows",

    "Witch of Love Potion": "Witch of Love Potion",
    "Magical and Hopeless": "Magical and Hopeless",
    "Sacred Battle": "Sacred Battle",

    "AN ORDEAL FROM GOD": "AN ORDEAL FROM GOD",

    "呑んべぇのレムリア": "A Drunkard's Lemuria",

    "キュアリアス上海古牌": "Curious old Shanghai tile",
    "神魔討綺伝 AN ORDEAL FROM GOD": "AN ORDEAL FROM GOD (Magus in Mystic Geometries)",

    "宵闇の魔術師": "Magician of the Twilight",
    "Magic of Life": "Magic of Life",
    "Plastic Space": "Plastic Space",
    "Frontal Attack": "Frontal Attack",
    "Inventive City": "Inventive City",
    "夢幻回廊": "Fantasy Corridor",
    "蓬莱幻想　～ far East": "Hourai Illusion ~ far East",
    "夜の鳩山を飛ぶ": "Fly above Hatoyama at night",
    "妖々跋扈　～ Speed Fox!": "Youkai Domination ~ Speed Fox!"
  },

  "toho-vote.info/form/vote_title.php": {
    "作品部門投票": "Works Poll",
    "投票ID": "Voting ID",
    "必須": "Required",
    "発行された10桁の投票IDを記入ください": "Please input your 10-character voting ID",
    "名前（任意）": "Name (Optional)",
    "ハンドルネームも可能です": "Nicknames are OK",
    "最大5件まで投票できます（重複不可）。名前は25文字、コメントは最大200文字までとなります。": "You can vote for up to 5 works (no duplicates). Names can be up to 25 characters, and comments can be 200 characters maximum.",
    "投票.1は一押し票として2票分のポイントとなります。": "Note, your #1 vote will count as 2 votes.",
    "投票.1": "Vote #1",
    "投票.2": "Vote #2",
    "投票.3": "Vote #3",
    "投票.4": "Vote #4",
    "投票.5": "Vote #5",
    "未選択": "Unselected",
    "コメント（任意）": "Comment (Optional)",
    "送信": "Submit",
    "投票部門選択に戻る": "Return to Voting Category Menu",

    "旧作": "PC-98",
    "WinSTG作品": "Windows",
    "黄昏フロンティア作品": "Twilight Frontier",
    "音楽作品": "Music Works",
    "書籍作品": "Written Works"
  },

  "toho-vote.info/form/vote_questionnaire.php": {
    "投票者アンケート回答": "Voter Questionnaire",
    "投票ID": "Voting ID",
    "必須": "Required",
    "発行された10桁の投票IDを記入ください": "Please input your 10-character voting ID",
    "01.年齢": "01. Age",
    "回答しない": "No Answer",
    "02.性別": "02. Gender",
    "男性": "Male",
    "女性": "Female",
    "03.お住まいの地域": "03. Residence",
    "日本国外：東アジア（中国・台湾・韓国など）": "Outside Japan: East Asia (China, Taiwan, South Korea, etc)",
    "日本国外：東南アジア": "Outside Japan: Southeast Asia",
    "日本国外：南・中央・西アジア": "Outside Japan: South/Central/West Asia",
    "日本国外：ヨーロッパ": "Outside Japan: Europe",
    "日本国外：アフリカ": "Outside Japan: Africa",
    "日本国外：北アメリカ": "Outside Japan: North America",
    "日本国外：南アメリカ": "Outside Japan: South America",
    "日本国外：オセアニア": "Outside Japan: Oceania",
    "04.ノーコンテニューでクリアできた難易度": "04. On what difficulty can you clear each game without continues?",
    "東方紅魔郷　": "EoSD　",
    "東方妖々夢　": "PCB　",
    "東方永夜抄　": "IN　",
    "東方花映塚　": "PoFV　",
    "東方風神録　": "MoF　",
    "東方地霊殿　": "SA　",
    "東方星蓮船　": "UFO　",
    "東方神霊廟　": "TD　",
    "東方輝針城　": "DDC　",
    "東方紺珠伝（完全無欠）　": "LoLK (Pointdevice)　",
    "東方紺珠伝（レガシー）　": "LoLK (Legacy)　",
    "東方天空璋　": "HSiFS　",
    "東方鬼形獣　": "WBaWC　",
    "未購入": "Not Played",
    "Easy未クリア": "No Easy Clear",
    "Easyクリア": "Easy Clear",
    "Normalクリア": "Normal Clear",
    "Hardクリア": "Hard Clear",
    "Lunaticクリア": "Lunatic Clear",
    "05.現在購読している雑誌連載作品": "05. Currently-subscribed publications",
    "東方茨歌仙　\n        ": "WaHH　",
    "東方三月精　\n        ": "VFiS　",
    "東方香霖堂　": "CoLA　",
    "※ここでの東方香霖堂は外來韋編連載分を指します。": "(Here Curiosities in Lotus Asia refers to the Strange Creators of Outer World serialization.)",
    "東方智霊奇伝　\n        ": "Chireikiden　",
    "東方酔蝶華　\n        ": "Suichouka　",
    "購入していない": "Don't buy",
    "単行本が出たら購入している": "Buy the tankobon volumes",
    "連載誌（Febri）を継続購入している": "Buy the serialization (Febri)",
    "連載誌（コンプエース）を継続購入している": "Buy the serialization (Comp Ace)",
    "連載誌（外來韋編）を購入した": "Bought the serialization (Strange Creators of Outer World)",
    "読んでいない": "Don't read",
    "Comic Walkerで読んでいる": "Read on Comic Walker",
    "ニコニコ静画で読んでいる": "Read on Nico Nico Seiga",
    "東方我楽多叢誌で読んでいる": "Read on Strange Articles of the Outer World",
    "06.東方Projectに魅力を感じているところ（複数回答可）": "06. What draws you into the Touhou Project series?",
    " 音楽": "Music",
    " ゲーム性": "Games",
    " キャラクタ": "Characters",
    " ストーリー": "Story",
    " 世界観": "Universe/Setting",
    " 二次創作作品": "Derivative Works",
    " 東方作品を通じた交流": "Social interaction",
    "07.東方Projectを知った時期": "07. When did you get into the Touhou Project series?",
    "旧作～秋霜玉（2000年12月）": "PC-98 ~ Shuusou Gyoku (2000/12)",
    "秋霜玉～紅魔郷（2002年8月）": "Shuusou Gyoku ~ EoSD (2002/08)",
    "紅魔郷～妖々夢（2003年8月）": "EoSD ~ PCB (2003/08)",
    "妖々夢～永夜抄（2004年8月）": "PCB ~ IN (2004/08)",
    "永夜抄～萃夢想（2004年12月）": "IN ~ IaMP (2004/12)",
    "萃夢想～花映塚（2005年8月）": "IaMP ~ PoFV (2005/08)",
    "花映塚～文花帖（2005年12月）": "PoFV ~ StB (2005/12)",
    "文花帖～求聞史紀（2006年12月）": "StB ~ PMiSS (2006/12)",
    "求聞史紀～風神録（2007年8月）": "PMiSS ~ MoF (2007/08)",
    "風神録～地霊殿（2008年8月）": "MoF ~ SA (2008/08)",
    "地霊殿～星蓮船（2009年8月）": "SA ~ UFO (2009/08)",
    "星蓮船～妖精大戦争（2010年8月）": "UFO ~ FW (2010/08)",
    "妖精大戦争～神霊廟（2011年8月）": "FW ~ TD (2011/08)",
    "神霊廟～求聞口授（2012年4月）": "TD ~ SoPM (2012/04)",
    "求聞口授～輝針城（2013年8月）": "SoPM ~ DDC (2013/08)",
    "輝針城～アマノジャク（2014年5月）": "DDC ~ ISC (2014/05)",
    "アマノジャク～紺珠伝（2015年8月）": "ISC ~ LoLK (2015/08)",
    "紺珠伝～旧約酒場（2016年8月）": "LoLK ~ Old Adam (2016/08)",
    "旧約酒場～天空璋（2017年8月）": "Old Adam ~ HSiFS (2017/08)",
    "天空璋～鬼形獣（2019年8月）": "HSiFS ~ WBaWC (2019/08)",
    "鬼形獣～現在": "WBaWC ~ Current",
    "08.東方Projectを知ったきっかけ": "08. How did you first discover the Touhou Project series?",
    "学校、部活、家族などオフラインでのつながりから教えてもらった": "School, Clubs, Family, or other offline connection",
    "オンラインゲーム、チャット（IRC）などネットでのつながりから教えてもらった": "Online game, Chat (IRC), or otherwise through online friends",
    "個人サイト、ブログ、ニュースサイトなどで話題になっているのをみて知った": "Personal site, Blogs, News sites, etc",
    "pixiv、ニジエ、TINAMIなどイラストSNSで話題になっているのをみて知った": "Pixiv, Nijie, TINAMI, etc illustration sites",
    "2ちゃんねる、ふたば、したらばなど匿名掲示板で話題になっているのをみて知った": "2ch, Futaba, Shitaraba etc online anonymous BBS",
    "ニコニコ動画（生放送なども含む）で話題になっているのをみて知った": "Nico Nico Douga (including live broadcasts)",
    "Youtubeなどその他の動画サイトで話題になっているのをみて知った": "Youtube or other video sharing sites",
    "Twitterで話題になっているのをみて知った": "Twitter",
    "雑誌連載、雑誌記事、TV番組などをみて知った": "Magazines, TV",
    "同人誌即売会（コミケなど）、サークル告知などでみかけて知った": "Doujinshi events (Comiket etc) or doujin circle announcements",
    "同人ショップ、一般書店などでみかけて知った": "Doujin shops or other stores",
    "音楽ゲームに東方曲があるのをみて知った": "Rhythm games that have Touhou music in them",
    "面白いゲームを探していたときにみつけた": "Found while looking for interesting games",
    "スマホアプリの二次創作ゲームで知った": "Touhou mobile game derivative works",
    "09.コミケや例大祭など同人誌即売会に参加するときの目当てはなんですか？（複数回答可）": "09. If you attend doujin events like Comiket and Reitaisai, what are your main activities there? (multiple answer)",
    " 参加していない": "Do not participate",
    " 公式原作の購入": "Buy official works",
    " 同人誌作品の購入": "Buy doujinshi",
    " 音楽同人作品の購入": "Buy doujin music",
    " 同人ソフト作品の購入": "Buy doujin games",
    " 同人グッズ作品の購入": "Buy doujin goods",
    " 企業制作作品の購入": "Buy corporate works",
    " 作品頒布（サークル）": "Distribute works (as a circle)",
    " 裏方作業（スタッフ）": "Staff",
    " サークルや友人との交流": "Interaction with circles and friends",
    " コスプレ（する側）": "Performing cosplay",
    " コスプレ（見る・撮影する側）": "Watching/photographing cosplay",
    " 音ゲーなどのコラボ企画": "Corporate collab events (for rhythm games, etc)",
    " 音楽ライブ（併催されるとき）": "Live concerts (when applicable)",
    "\n        \n        ※「参加していない」にチェックを入れると、それ以外の全てのチェックが無効になります。\n        ": "※ If you select 'Do not participate', all others selected will not be counted.",
    "10.これまでに東方Project（シリーズ）人気投票へ投票したことはありますか？": "10. Have you voted in the Touhou Series Popularity Contest before?",
    "今回がはじめて": "First time",
    "過去1～3回投票したことがある": "Voted past 1~3 years",
    "過去4回以上投票したことがある": "Voted past 4+ years",
    "送信": "Submit",
    "投票部門選択に戻る": "Return to Voting Category Menu"
  },

  "toho-vote.info/Faq.php": {
    "投票全般": "General",
    "Ｑ．携帯電話・スマートフォンから投票できますか？": "Q. Can I vote from my cell phone?",
    "Ａ．投票可能ですが、サポート対象外となります。エラーなどで投票できない場合はネットカフェや知り合いのPC等、携帯電話以外の環境から投票してください。": "A. You can vote, but support for phones is not guaranteed. If errors occur such that you cannot vote, please vote from a different location, such as a net cafe or a friend's PC, instead. ",
    "Ｑ．コメント欄は記入しないといけないのですか？": "Q. Do I need to fill out the comment field?",
    "Ａ．無記入のまま投票しても問題ありません。": "A. Filling out the comment field isn't necessary.",
    "Ｑ．持ち票分投票したいものがありません": "Q. I don't want to fill out all the spots for votes.",
    "Ａ．投票したい数だけ選択し、残りは未選択で投票してください。": "A. Vote for as many as you would like, then leave the others unselected.",
    "Ｑ．海外からも投票できますか？": "Q. Can people outside Japan vote?",
    "Ａ．投票可能です。": "A. Yes.",
    "Ｑ．兄弟等で同一PCから投票しても大丈夫でしょうか？": "Q. Will it be okay if I vote from the same computer as my siblings, etc.?",
    "Ａ．多重投票と誤判断される可能性はゼロとは言い切れませんが、コメントに投票理由までしっかり書かれていればほぼ大丈夫です。": "A. While it's impossible to say with 100% certainty that your votes won't be mistakenly judged to be duplicate votes, if you include the voting reason in the comment, it should be fine.",
    "Ｑ．フリーメールアドレスでやむを得ない場合、きちんとコメントすれば大丈夫なのですか？": "Q. I have no choice but to vote using a temporary e-mail address; will it be all right if I fill out the comment field nicely?",
    "Ａ．多重投票でなければ問題ありません。": "A. As long as it's not a duplicate vote, there won't be any problem.",
    "（補足）最近、使い捨てのワンタイムメールアドレスでの投票が多くなっています。やむを得ない場合は使用禁止ではありませんが、多重投稿と誤判断される可能性がある点ご注意ください。": "Note: Recently there has been a surge in votes from one-time-use emails. In case using one is unavoidable they will not be prohibited, but please be aware that there is a higher likelihood that these may be marked as duplicates or invalid votes.",
    "Ｑ．投票時のコメントは何文字まで入力できるのでしょうか？": "Q. What is the maximum number of characters allowed for comments at voting time?",
    "Ａ．全角200文字までとなります。": "A. 200 full-width characters (or 400 ASCII characters.)",
    "Ｑ．投票用IDが届きません。": "Q. My voting ID email never arrived.",
    "Ａ．IDが記載されたメールが届くまで時間がかかることがあります。また、メールアドレスの受信拒否設定をしている場合、メールをお送りすることができません。｢@thwiki.info｣（ID送付用）および｢gmail.com｣（お問い合わせ返信用）を受信できるよう設定してください（※設定されていない場合、お問い合わせを頂いても返信ができません）。": "A. It can sometimes take time for the ID to reach the listed email. Also, if you do any mail filtering (even if done automatically through your email service), it may fail to arrive. Please whitelist the domains \"@thwiki.info\" (for ID requests) and \"gmail.com\" (for enquiries) so all such emails can go through (if gmail is not whitelisted, even if you make an enquiry, replies may not arrive).",
    "一日以上届かない場合は、[発行フォーム]にて同じメールアドレスを入力することで、メールを再送できます。それでもメールが届かない場合は": "If more than a day has passed, you can resubmit the Voting ID form using the same email. If you've done all these steps and still don't receive the email, please contact us using the ",
    "[フォーム]": "[Contact Form]",
    "あるいは": " or through ",
    "[Twitter]": "[Twitter]",
    "よりお問い合わせください。": ".",

    "人妖部門関連": "Character Poll",
    "Ｑ．黒リリーは投票できますか？": "Q. Can I vote for Lily Black?",
    "Ａ．白リリーと同一枠になります。": "A. She is included as the \"Lily White\" option.",
    "\n            （※10/08/21の「枯れラジ」内にて、白リリーと黒リリーは同一人物であるというZUN氏のコメントがありました）": "(※ In the \"Kare Radio\" broadcast on Aug 21, 2010, ZUN commented that Lily White and Lily Black are the same character.)",
    "Ｑ．冴月麟は投票できますか？": "Q. Can I vote for Rin Satsuki?",
    "Ａ．公式には存在しないキャラクタですので、対象外となります。": "A. As a character which does not officially exist, she will not be included.",
    "Ｑ．投票したいキャラの項目がないのですが": "Q. There's no option for the character I want to vote for...",
    "Ａ．西方/黄昏酒場/神主（ZUN）は東方シリーズの登場キャラクタではないため、対象外となっています。また、上海人形・UFO以外の無生物（陰陽玉、アイテム等）は対象外となります。": "A. As Seihou characters, Uwabami Breakers characters, and ZUN are not characters that have appeared in the Touhou series, they will not be included. In addition, inanimate objects (Yin-Yang orbs, gameplay items, etc) except for the Shanghai Doll and UFOs will not be included.",
    "Ｑ．封魔録1面中ボスや同3ボスは無生物なので対象外となるのはわかりますが、それ以外の旧作中ボスは投票対象とできないのですか？": "Q. Story of Eastern Wonderland's Stage 1 midboss and Stage 3 boss are inanimate objects, so I can understand why they're not included, but can't I vote for other PC-98 midbosses?",
    "Ａ．第14回から投票対象となりました。": "A. As of the 14th contest they can be voted for.",
    "Ｑ．雑魚妖精について、メイド妖精等に個別枠を設けてもらえませんでしょうか？": "Q. Regarding the fairy mooks, will there be separate options for fairy maids, etc?",
    "Ａ．固有名詞の無いキャラクタやモブキャラクタに関しては、票の分散や知名度などから判断して種族毎に同一枠としています。": "A. Characters without proper names will be included in the options named after their race.",
    "Ｑ．蓬莱人形（CD-R版）のレーベル面に描かれている子は投票対象外でしょうか？": "Q. Can I vote for the girl on the Dolls in Pseudo Paradise label?",
    "Ａ．第13回より投票対象となっています。": "A. As of the 13th contest they can be voted for.",
    "Ｑ．茨木童子の腕、奸佞邪知の鬼は投票対象ですか？": "Can I vote for Ibaraki Douji's Arm, or the Cunning and Treacherous Oni?",
    "Ａ．第16回より投票対象となっています。詳しくは": "As of the 16th contest they can be voted for. For details please refer to ",
    "茨木華扇について": "About Kasen Ibaraki",
    "をご覧ください。": ".",


    "音楽部門関連": "Music Poll",
    "Ｑ．音楽CDのアレンジ曲と原曲の扱いはどうなりますか？": "Q. How will votes for arrangements of original songs appearing on the music CDs be handled?",
    "Ａ．投票画面では別項目になっていますが、集計時にアレンジ曲と原曲は同一票にまとめられますので好きな方を選択して投票してください。なお両方に投票することはできませんが、": "A. Arrangements will be displayed as separate items on the voting screen, but votes for the arrangements and their original songs will be counted together during vote totaling. Please vote for the arrangement you like the most. You cannot vote for both the original song and the arrangement, ",
    "発表時にどの作品の曲に何票投票されたかを併せて公表する予定です": "but the counts of which songs were voted for will be included in the results ",
    "（例：": "(e.g., see ",
    "第12回の投票の詳細集計結果": "the detailed results from the 12th contest",
    "）。": ").",
    "Ｑ．恋色マジックと恋色マスタースパークなどの扱いはどうなりますか？": "Q. How are you treating the cases like \"Love-coloured Magic\" and \"Love-coloured Master Spark\"?",
    "Ａ．": "A. Please refer to the ",
    "曲名違いのアレンジで同一票にまとめられる曲一覧": "list of arrangements which will be counted together",
    "を参照してください。": ".",
    "Ｑ．「幽雅に咲かせ、墨染めの桜」と「ボーダーオブライフ」は、曲名違いのアレンジではないのですか？": "Q. Aren't \"Bloom Nobly, Ink-Black Cherry Blossoms ~ Border of Life\" and \"Border of Life\" different arrangements of the same song?",
    "Ａ．この投票では別楽曲として扱うこととしています。": "A. In this poll, they are treated as different songs.",

    "アンケート関連": "Questionnaire",
    "Ｑ．投票者アンケートのクリア状況には処理落ち率は追加されないのでしょうか？": "Q. Regarding the survey on game clears, aren't frame drop rates going to be included?",
    "Ａ．そこまで厳密な集計はしない予定です。": "A. We do not intend to go into such strict level of detail.",

    "その他": "Other",
    "Ｑ．スペルカードの投票をする予定は無いのでしょうか？": "Q. Are there any plans to include a Spell Card poll?",
    "Ａ．今のところ実施予定はありません。": "A. For the time being it will not be implemented.",
    "Ｑ．pixiv等で絵を描いているものですが、宣伝を兼ねた絵を描いてもよろしいでしょうか。": "Q. Can I use pictures I've drawn on Pixiv, etc. as publicity images?",
    "Ａ．宣伝は歓迎しております。また、投稿時にハッシュタグ「#toho_vote16」「第16回東方Project人気投票」を付けることを推奨しております。また、参加者が自由に登録できる": "A. Publicity is welcome. Using the hashtags \"#toho_vote16\" and \"第16回東方Project人気投票\" is recommended. Participants can also put links to these works in the ",
    "支援作品リンク集": "Cheering",
    "を用意しておりますので、こちらもぜひご活用いただければと思います。": " page to show their support."
  },

  "toho-vote.info/Rule.php": {
    "去年からの変更点": "Differences from Previous Year",
    "今年は「ベストパートナー部門」は開催いたしません。": "This year there will be no Best Partner Poll.",
    "新規追加対象は": "New additions to vote for are listed in the ",
    "[投票対象一覧]": "voting list",
    "および": " as well as the ",
    "[曲名違いのアレンジで同一票にまとめられる曲一覧]": "list of arrangements to be counted together",
    "を参照してください。": ".",
    "新規投票対象に入れたい項目がある場合、2/20 23:59までにお問い合わせフォームよりご連絡ください。追加を検討します（必ずしも追加するとは限りません。また、可否について返信は行いません）。": "If you wish for any new additions to vote nominees, until 2/20 23:59 you may use the contact form to make requests, and they will be considered. (However, they will not necessarily be added. There will also not necessarily be an accept/reject reply.)",
    "投票のきまり": "Voting Regulations",
    "企画の大まかな流れ": "Schedule",
    "【支援しよう】": "【Let's Cheer!】",
    "　支援作品を登録して好きなキャラクタ・音楽・作品を応援（1/5 ～ 2/2）": "Cheering on your favorite characters/music/works by submitting content (1/5 ~ 2/2)",
    "【投票IDを発行】": "【Issue Voting ID】",
    "ID発行フォームにてメールアドレスを送信（1/26 12:00 ～ 2/2 23:59）": "Sending out Voting IDs by email through the ID Form (1/26 12:00 ~ 2/2 23:59)",
    "【投票しよう】": "【Let's Vote!】",
    "　入力したアドレスに届いた投票IDを使用し、各部門へ投票（1/27 0:00 ～ 2/2 23:59）": "Voting in polls using the Voting ID associated with your email (1/27 0:00 ~ 2/2 23:59)",
    "【結果の発表】": "【Publish Results】",
    "　速報は1/20予定。さらに後日、詳細な集計結果を発表": "The results summary is planned for 2/3. Following this, a breakdown of the results will be published later.",
    "ルール": "Rules",
    // "投票権は各部門につき": "",
    // "一人一回": "",
    // "です。重複投票は無効となります。": "",
    // "投票IDは全部門共通です。同じIDで1回ずつ投票できます。": "",
    // "全ての部門に参加する必要はありません。": "",
    // "投票後、投票期間終了までは投票先やコメントを修正することができます。": "",
    // "投票時に記入されたコメントは結果発表時に掲載されます。ただし不適切と判断したものについては削除することがあります。": "",
    // "ID発行に、フリーメールアドレスは非推奨としますが、やむを得ない場合は可とします。": "",
    // "投票対象については": "",
    // "[投票対象一覧]": "",
    // "を参照してください。": "",
    // "[よくある質問]": "",
    // "もあわせてご参照ください。": "",
    // "「東方憑依華」のキャラクターおよびBGMについては、投票対象となりますが、固有名詞を隠した状態でのエントリーとなります。支援登録も可能ですが、できるだけ固有名詞を伏せる形での登録をお願いします。": "",
    // "なおコメント欄など、ネタバレを完全に防ぐことは確約しかねます。ネタバレを避けたい方にはご不便をおかけしますが、ご理解をお願いいたします。": "",
    // "各部門の概要": "",
    // "人妖部門": "",
    // "最大7キャラクタまで投票可能（そのうち一押しを1人選び、そのキャラクタには2ポイント）": "",
    // "音楽部門": "",
    // "最大10曲まで投票可能 （そのうち一押しを1曲選び、その曲には2ポイント） ": "",
    // "作品部門": "",
    // "最大5作まで投票可能 （そのうち一押しを1作選び、その作品には2ポイント） ": "",
    // "投票者アンケート": "",
    // "主にプレイ作品、クリア状況など": "",
    // "各部門はそれぞれ個別に回答する形となります（回答しない部門があっても構いません）": "",
    // "投票時に記入されたコメントは結果発表時に掲載されます。ただし不適切と判断したものについては削除することがあります。": "",
    // "投票期間": "",
    // "支援作品リンク受付期間": "",
    // "2019年1月05日（日）00:00 ～ 2月2日（土）23:59": "",
    // "投票用ID発行期間": "",
    // "2019年": "",
    // "1月27日（土）12:00": "",
    // " ～ 2月2日（土）23:59": "",
    // "投票受付期間": "",
    // "2019年1月27日（日）00:00 ～ 2月2日（土）23:59": "",
    // "結果発表予定日": "",
    // "2019年2月3日（日） 速報予定（※後日、詳細な集計結果を発表予定）": "",
    // "投票用IDを投票期間より先行して発行できます。": "",
    // "負荷分散のため、事前のID発行にご協力をお願いします。": "",
    // "個人情報の取扱いについて": "",
    // "不正防止のため、投票にはメールアドレスが必須となります。投票時に入力されたメールアドレスは厳重に管理し、投票ID発行と集計時の照合以外での目的に使用されることはありません。": "",
    // "\n        また、投票集計完了後に廃棄いたします。": "",
    // "支援作品の公開について": "",
    // "応援するキャラクタ/楽曲/作品を支援するための作品を登録できる": "",
    // "[フォーム]": "",
    // "を用意しております。こちらもぜひご活用いただければと思います。\n\t\t": "",
    // "また、各種投稿サイトでぜひともハッシュタグ「#toho_vote15」や「第15回東方Project人気投票」タグをつけて投稿ください。": "",
    // "注意事項・リンクに関して": "",
    // "この人気投票は非公式の企画です。投票に関して上海アリス幻樂団他へのお問い合わせはご遠慮ください。": "",
    // "宣伝は自由にお願いいたします。リンク先はhttp://thwiki.info/th/vote15/でお願いします。": "",
    // "\n        Twetterの公式ハッシュタグは#toho_vote15となります。": "",
    // "※バナー画像は持ち帰り推奨。": ""
  }
};
