var touhoudict = {
  "en_jp":{
    "characters": {
      "Reimu Hakurei": "博麗 霊夢",
      "Marisa Kirisame": "霧雨 魔理沙",
      "Rumia": "ルーミア",
      "Daiyousei": "大妖精",
      "Cirno": "チルノ",
      "Hong Meiling": "紅 美鈴",
      "Koakuma": "小悪魔",
      "Patchouli Knowledge": "パチュリー・ノーレッジ",
      "Sakuya Izayoi": "十六夜 咲夜",
      "Remilia Scarlet": "レミリア・スカーレット",
      "Flandre Scarlet": "フランドール・スカーレット",
      "Letty Whiterock": "レティ・ホワイトロック",
      "Chen": "橙",
      "Alice Margatroid": "アリス・マーガトロイド",
      "Lily White": "リリーホワイト",
      "Lunasa Prismriver": "ルナサ・プリズムリバー",
      "Merlin Prismriver": "メルラン・プリズムリバー",
      "Lyrica Prismriver": "リリカ・プリズムリバー",
      "Youmu Konpaku": "魂魄 妖夢",
      "Yuyuko Saigyouji": "西行寺 幽々子",
      "Ran Yakumo": "八雲 藍",
      "Yukari Yakumo": "八雲 紫",
      "Wriggle Nightbug": "リグル・ナイトバグ",
      "Mystia Lorelei": "ミスティア・ローレライ",
      "Keine Kamishirasawa": "上白沢 慧音",
      "Tewi Inaba": "因幡 てゐ",
      "Reisen Udongein Inaba": "鈴仙・優曇華院・イナバ",
      "Eirin Yagokoro": "八意 永琳",
      "Kaguya Houraisan": "蓬莱山 輝夜",
      "Fujiwara no Mokou": "藤原 妹紅",
      "Suika Ibuki": "伊吹 萃香",
      "Aya Shameimaru": "射命丸 文",
      "Medicine Melancholy": "メディスン・メランコリー",
      "Yuuka Kazami": "風見 幽香",
      "Komachi Onozuka": "小野塚 小町",
      "Eiki Shiki, Yamaxanadu": "四季映姫・ヤマザナドゥ",
      "Shizuha Aki": "秋 静葉",
      "Minoriko Aki": "秋 穣子",
      "Hina Kagiyama": "鍵山 雛",
      "Nitori Kawashiro": "河城 にとり",
      "Momiji Inubashiri": "犬走 椛",
      "Sanae Kochiya": "東風谷 早苗",
      "Kanako Yasaka": "八坂 神奈子",
      "Suwako Moriya": "洩矢 諏訪子",
      "Iku Nagae": "永江 衣玖",
      "Tenshi Hinanawi": "比那名居 天子",
      "Kisume": "キスメ",
      "Yamame Kurodani": "黒谷 ヤマメ",
      "Parsee Mizuhashi": "水橋 パルスィ",
      "Yuugi Hoshiguma": "星熊 勇儀",
      "Satori Komeiji": "古明地 さとり",
      "Rin Kaenbyou": "火焔猫 燐",
      "Utsuho Reiuji": "霊烏路 空",
      "Koishi Komeiji": "古明地 こいし",
      "Nazrin": "ナズーリン",
      "Kogasa Tatara": "多々良 小傘",
      "Ichirin Kumoi": "雲居 一輪",
      "Unzan": "雲山",
      "Minamitsu Murasa": "村紗 水蜜",
      "Shou Toramaru": "寅丸 星",
      "Byakuren Hijiri": "聖 白蓮",
      "Nue Houjuu": "封獣 ぬえ",
      "Giant Catfish": "大ナマズ",
      "Hatate Himekaidou": "姫海棠 はたて",
      "Kyouko Kasodani": "幽谷 響子",
      "Yoshika Miyako": "宮古 芳香",
      "Seiga Kaku": "霍 青娥",
      "Soga no Tojiko": "蘇我 屠自古",
      "Mononobe no Futo": "物部 布都",
      "Toyosatomimi no Miko": "豊聡耳 神子",
      "Mamizou Futatsuiwa": "二ッ岩 マミゾウ",
      "Hata no Kokoro": "秦 こころ",
      "Wakasagihime": "わかさぎ姫",
      "Sekibanki": "赤蛮奇",
      "Kagerou Imaizumi": "今泉 影狼",
      "Benben Tsukumo": "九十九 弁々",
      "Yatsuhashi Tsukumo": "九十九 八橋",
      "Seija Kijin": "鬼人 正邪",
      "Shinmyoumaru Sukuna": "少名 針妙丸",
      "Raiko Horikawa": "堀川 雷鼓",
      "Sumireko Usami": "宇佐見 菫子",
      "Seiran": "清蘭",
      "Ringo": "鈴瑚",
      "Doremy Sweet": "ドレミー・スイート",
      "Sagume Kishin": "稀神 サグメ",
      "Clownpiece": "クラウンピース",
      "Junko": "純狐",
      "Hecatia Lapislazuli": "ヘカーティア・ラピスラズリ",
      "SinGyoku": "シンギョク",
      "YuugenMagan": "ユウゲンマガン",
      "Meira": "エリス",
      "Sariel": "サリエル",
      "Kikuri": "キクリ",
      "Konngara": "コンガラ",
      "Genjii": "玄爺",
      "Rika": "里香",
      "Elis": "明羅",
      "Mima": "魅魔",
      "Ellen": "エレン",
      "Kotohime": "小兎姫",
      "Kana Anaberal": "カナ・アナベラル",
      "Rikako Asakura": "朝倉 理香子",
      "Chiyuri Kitashirakawa": "北白河 ちゆり",
      "Yumemi Okazaki": "岡崎 夢美",
      "Orange": "オレンジ",
      "Kurumi": "くるみ",
      "Elly": "エリー",
      "Mugetsu": "夢月",
      "Gengetsu": "幻月",
      "Sara": "サラ",
      "Louise": "ルイズ",
      "Yuki": "ユキ",
      "Mai": "マイ",
      "Yumeko": "夢子",
      "Shinki": "神綺",
      "Dolls in Pseudo Paradise CD Jacket Girl": "蓬莱人形ジャケットイラストの娘",
      "Dolls in Pseudo Paradise CD Label Girl": "蓬莱人形レーベルイラストの娘",
      "Renko Usami": "宇佐見 蓮子",
      "Maribel Hearn": "マエリベリー・ハーン",
      "Hieda no Akyuu": "稗田 阿求",
      "Rinnosuke Morichika": "森近 霖之助",
      "Sunny Milk": "サニーミルク",
      "Luna Child": "ルナチャイルド",
      "Star Sapphire": "スターサファイア",
      "Watatsuki no Toyohime": "綿月 豊姫",
      "Watatsuki no Yorihime": "綿月 依姫",
      "Rei’sen": "レイセン",
      "Kasen Ibaraki": "茨木 華扇",
      "Kosuzu Motoori": "本居 小鈴",
      "Ruukoto": "るーこと",
      "Mimi-chan": "ミミちゃん",
      "Youki Konpaku": "魂魄 妖忌",
      "Layla Prismriver": "レイラ・プリズムリバー",
      "Thermonuclear Deity Hisou Tensoku": "核熱造神ヒソウテンソク",
      "Myouren": "命蓮",
      "Bishamonten": "毘沙門天",
      "Chang'e": "嫦娥",
      "Unnamed Book-Reading Youkai": "名無しの本読み妖怪",
      "Tsuchinoko": "ツチノコ",
      "Sake Bug": "酒虫",
      "Moon Capital Gate Guards": "月の都の門番",
      "Mizue no Uranoshimako": "水江浦島子",
      "Unshou": "岩笠",
      "Konohana-Sakuyahime": "木花咲耶姫",
      "Shirou Sendai": "仙台四郎（福の神）",
      "Iwakasa": "運松",
      "Kutsutsura": "座敷童",
      "Hobgoblin": "ホフゴブリン",
      "Manzairaku": "万歳楽",
      "Unnamed Dormouse (Yamane)": "ヤマネ",
      "Keseran-pasaran": "ケセランパサラン",
      "Kosuzu Motoori's Parents": "小鈴の両親",
      "Enenra": "煙々羅",
      "Tupai": "チュパカブラ",
      "Zashiki-warashi": "沓頬",
      "Unnamed Snake Youkai": "ウワバミ",
      "Unnamed Jinyou (Fortune Teller)": "易者",
      "Anxious Moustached Villager": "抗鬱薬おじさん",
      "Nameemon (Kosuzu's stuffed slug)": "なめえもん",
      "Salt Merchant": "塩屋敷の旦那",
      "Fairy (Maid, Sunflower, etc.)": "妖精（メイド妖精・ひまわり妖精他）",
      "Ghosts (including vengeful spirits, divine spirits, bakebake)": "幽霊（怨霊、神霊、化け化け含む）",
      "Kedama": "毛玉",
      "UFOs (red, blue, green, etc.)": "UFO（赤・青・緑、その他）",
      "Rabbits (Moon rabbits, Eientei youkai rabbits, etc)": "兎（玉兎、永遠亭の妖怪兎他）",
      "Tanuki (Bake-danuki, Noteppou, etc)": "狸（化け狸、野鉄砲他）",
      "Kitsune (Youkai kitsune, Unnamed fox student, etc)": "狐（妖怪狐、狐の子他）",
      "Crows (Hell ravens, Yukari and Aya's familiars, etc.)": "カラス（地獄鴉、紫・文の使い魔他）",
      "Kappa (including yamawaro)": "河童（山童含む）",
      "Tengu (Kourindou Tengu, Great Tengu, etc)": "天狗（香霖堂の天狗、大天狗他）",
      "Dragons (Dragon child, Unnamed evil dragon, etc)": "龍（子龍、邪龍他）",
      "Alice’s Dolls (Shanghai, Hourai, Ooedo, etc.)": "アリスの人形（上海、蓬莱、大江戸他）",
      "Kasen's animals (Kume, Kanda, Raijuu, Houso, Jinkenmen, etc)": "華扇の動物（久米、竿打、雷獣、彭祖、人面犬他）",
      "Summoned Gods (Amaterasu, Izunome, etc.)": "神降ろしの神霊（天照、伊豆能売他）",
      "Urban legend entities (Okiku-san, Hasshaku-sama)": "都市伝説の怪異（お菊さん、八尺さま他）",
    },
    "music": {},
    "works": {}
  },
  "jp_en": {
    "characters": {},
    "music": {},
    "works": {}
  }
};

// populate jp->en

for(k of Object.keys(touhoudict.en_jp.characters)){
  touhoudict.jp_en.characters[touhoudict.en_jp.characters[k]] = k;
}

// the stuff that does the work

var translate_all = function(dict, q){
  if(!touhoudict.hasOwnProperty(dict)){
    console.error("touhoudict: Not a valid dictionary (" + Object.keys(touhoudict).join(", ") + ")");
    return false;
  }
  var opts = document.querySelectorAll(q);
  var c = 0;
  for(var i=0; i<opts.length; i++){
    var e = opts[i];
    if(touhoudict[dict].characters.hasOwnProperty(e.textContent)){
      e.textContent = touhoudict[dict].characters[e.textContent];
      c++;
    }
  }
  console.log("touhoudict: Translated " + c + " instances.");
  return (c > 0);
}

var jp2en_all = translate_all.bind(this, "jp_en");
var en2jp_all = translate_all.bind(this, "en_jp");

// actually run now

jp2en_all("option");
